/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gusto.embedded_api;

import static com.gusto.embedded_api.operations.Operations.AsyncRequestOperation;

import com.gusto.embedded_api.models.components.VersionHeader;
import com.gusto.embedded_api.models.operations.GetV1ContractorDocumentPdfRequest;
import com.gusto.embedded_api.models.operations.GetV1ContractorDocumentRequest;
import com.gusto.embedded_api.models.operations.GetV1ContractorDocumentsRequest;
import com.gusto.embedded_api.models.operations.PutV1ContractorDocumentSignRequest;
import com.gusto.embedded_api.models.operations.PutV1ContractorDocumentSignRequestBody;
import com.gusto.embedded_api.models.operations.async.GetV1ContractorDocumentPdfRequestBuilder;
import com.gusto.embedded_api.models.operations.async.GetV1ContractorDocumentPdfResponse;
import com.gusto.embedded_api.models.operations.async.GetV1ContractorDocumentRequestBuilder;
import com.gusto.embedded_api.models.operations.async.GetV1ContractorDocumentResponse;
import com.gusto.embedded_api.models.operations.async.GetV1ContractorDocumentsRequestBuilder;
import com.gusto.embedded_api.models.operations.async.GetV1ContractorDocumentsResponse;
import com.gusto.embedded_api.models.operations.async.PutV1ContractorDocumentSignRequestBuilder;
import com.gusto.embedded_api.models.operations.async.PutV1ContractorDocumentSignResponse;
import com.gusto.embedded_api.operations.GetV1ContractorDocument;
import com.gusto.embedded_api.operations.GetV1ContractorDocumentPdf;
import com.gusto.embedded_api.operations.GetV1ContractorDocuments;
import com.gusto.embedded_api.operations.PutV1ContractorDocumentSign;
import com.gusto.embedded_api.utils.Headers;
import java.lang.String;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;


public class AsyncContractorDocuments {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final ContractorDocuments syncSDK;

    AsyncContractorDocuments(ContractorDocuments syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public ContractorDocuments sync() {
        return syncSDK;
    }


    /**
     * Get all contractor documents
     * 
     * <p>Get a list of all contractor's documents
     * 
     * <p>scope: `contractor_documents:read`
     * 
     * @return The async call builder
     */
    public GetV1ContractorDocumentsRequestBuilder getAll() {
        return new GetV1ContractorDocumentsRequestBuilder(sdkConfiguration);
    }

    /**
     * Get all contractor documents
     * 
     * <p>Get a list of all contractor's documents
     * 
     * <p>scope: `contractor_documents:read`
     * 
     * @param contractorUuid The UUID of the contractor
     * @return {@code CompletableFuture<GetV1ContractorDocumentsResponse>} - The async response
     */
    public CompletableFuture<GetV1ContractorDocumentsResponse> getAll(String contractorUuid) {
        return getAll(contractorUuid, Optional.empty());
    }

    /**
     * Get all contractor documents
     * 
     * <p>Get a list of all contractor's documents
     * 
     * <p>scope: `contractor_documents:read`
     * 
     * @param contractorUuid The UUID of the contractor
     * @param xGustoAPIVersion 
     * @return {@code CompletableFuture<GetV1ContractorDocumentsResponse>} - The async response
     */
    public CompletableFuture<GetV1ContractorDocumentsResponse> getAll(String contractorUuid, Optional<? extends VersionHeader> xGustoAPIVersion) {
        GetV1ContractorDocumentsRequest request =
            GetV1ContractorDocumentsRequest
                .builder()
                .contractorUuid(contractorUuid)
                .xGustoAPIVersion(xGustoAPIVersion)
                .build();
        AsyncRequestOperation<GetV1ContractorDocumentsRequest, GetV1ContractorDocumentsResponse> operation
              = new GetV1ContractorDocuments.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Get a contractor document
     * 
     * <p>Get a contractor document.
     * 
     * <p>scope: `contractor_documents:read`
     * 
     * @return The async call builder
     */
    public GetV1ContractorDocumentRequestBuilder get() {
        return new GetV1ContractorDocumentRequestBuilder(sdkConfiguration);
    }

    /**
     * Get a contractor document
     * 
     * <p>Get a contractor document.
     * 
     * <p>scope: `contractor_documents:read`
     * 
     * @param documentUuid The UUID of the document
     * @return {@code CompletableFuture<GetV1ContractorDocumentResponse>} - The async response
     */
    public CompletableFuture<GetV1ContractorDocumentResponse> get(String documentUuid) {
        return get(documentUuid, Optional.empty());
    }

    /**
     * Get a contractor document
     * 
     * <p>Get a contractor document.
     * 
     * <p>scope: `contractor_documents:read`
     * 
     * @param documentUuid The UUID of the document
     * @param xGustoAPIVersion 
     * @return {@code CompletableFuture<GetV1ContractorDocumentResponse>} - The async response
     */
    public CompletableFuture<GetV1ContractorDocumentResponse> get(String documentUuid, Optional<? extends VersionHeader> xGustoAPIVersion) {
        GetV1ContractorDocumentRequest request =
            GetV1ContractorDocumentRequest
                .builder()
                .documentUuid(documentUuid)
                .xGustoAPIVersion(xGustoAPIVersion)
                .build();
        AsyncRequestOperation<GetV1ContractorDocumentRequest, GetV1ContractorDocumentResponse> operation
              = new GetV1ContractorDocument.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Get the contractor document pdf
     * 
     * <p>Get the contractor document pdf.
     * 
     * <p>scope: `contractor_documents:read`
     * 
     * @return The async call builder
     */
    public GetV1ContractorDocumentPdfRequestBuilder getPdf() {
        return new GetV1ContractorDocumentPdfRequestBuilder(sdkConfiguration);
    }

    /**
     * Get the contractor document pdf
     * 
     * <p>Get the contractor document pdf.
     * 
     * <p>scope: `contractor_documents:read`
     * 
     * @param documentUuid The UUID of the document
     * @return {@code CompletableFuture<GetV1ContractorDocumentPdfResponse>} - The async response
     */
    public CompletableFuture<GetV1ContractorDocumentPdfResponse> getPdf(String documentUuid) {
        return getPdf(documentUuid, Optional.empty());
    }

    /**
     * Get the contractor document pdf
     * 
     * <p>Get the contractor document pdf.
     * 
     * <p>scope: `contractor_documents:read`
     * 
     * @param documentUuid The UUID of the document
     * @param xGustoAPIVersion 
     * @return {@code CompletableFuture<GetV1ContractorDocumentPdfResponse>} - The async response
     */
    public CompletableFuture<GetV1ContractorDocumentPdfResponse> getPdf(String documentUuid, Optional<? extends VersionHeader> xGustoAPIVersion) {
        GetV1ContractorDocumentPdfRequest request =
            GetV1ContractorDocumentPdfRequest
                .builder()
                .documentUuid(documentUuid)
                .xGustoAPIVersion(xGustoAPIVersion)
                .build();
        AsyncRequestOperation<GetV1ContractorDocumentPdfRequest, GetV1ContractorDocumentPdfResponse> operation
              = new GetV1ContractorDocumentPdf.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Sign a contractor document
     * 
     * <p>Sign a contractor document.
     * 
     * <p>scope: `contractor_documents:write`
     * 
     * @return The async call builder
     */
    public PutV1ContractorDocumentSignRequestBuilder sign() {
        return new PutV1ContractorDocumentSignRequestBuilder(sdkConfiguration);
    }

    /**
     * Sign a contractor document
     * 
     * <p>Sign a contractor document.
     * 
     * <p>scope: `contractor_documents:write`
     * 
     * @param documentUuid The UUID of the document
     * @param requestBody 
     * @return {@code CompletableFuture<PutV1ContractorDocumentSignResponse>} - The async response
     */
    public CompletableFuture<PutV1ContractorDocumentSignResponse> sign(String documentUuid, PutV1ContractorDocumentSignRequestBody requestBody) {
        return sign(
                documentUuid, Optional.empty(), Optional.empty(),
                requestBody);
    }

    /**
     * Sign a contractor document
     * 
     * <p>Sign a contractor document.
     * 
     * <p>scope: `contractor_documents:write`
     * 
     * @param documentUuid The UUID of the document
     * @param xGustoClientIp Optional header to supply the IP address. This can be used to supply the IP address for signature endpoints instead of the signed_by_ip_address parameter.
     * @param xGustoAPIVersion 
     * @param requestBody 
     * @return {@code CompletableFuture<PutV1ContractorDocumentSignResponse>} - The async response
     */
    public CompletableFuture<PutV1ContractorDocumentSignResponse> sign(
            String documentUuid, Optional<String> xGustoClientIp,
            Optional<? extends VersionHeader> xGustoAPIVersion, PutV1ContractorDocumentSignRequestBody requestBody) {
        PutV1ContractorDocumentSignRequest request =
            PutV1ContractorDocumentSignRequest
                .builder()
                .documentUuid(documentUuid)
                .xGustoClientIp(xGustoClientIp)
                .xGustoAPIVersion(xGustoAPIVersion)
                .requestBody(requestBody)
                .build();
        AsyncRequestOperation<PutV1ContractorDocumentSignRequest, PutV1ContractorDocumentSignResponse> operation
              = new PutV1ContractorDocumentSign.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
