/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gusto.embedded_api;

import static com.gusto.embedded_api.operations.Operations.AsyncRequestOperation;

import com.gusto.embedded_api.models.components.VersionHeader;
import com.gusto.embedded_api.models.operations.GetV1TokenInfoRequest;
import com.gusto.embedded_api.models.operations.RefreshAccessTokenRequest;
import com.gusto.embedded_api.models.operations.RefreshAccessTokenRequestBody;
import com.gusto.embedded_api.models.operations.async.GetV1TokenInfoRequestBuilder;
import com.gusto.embedded_api.models.operations.async.GetV1TokenInfoResponse;
import com.gusto.embedded_api.models.operations.async.RefreshAccessTokenRequestBuilder;
import com.gusto.embedded_api.models.operations.async.RefreshAccessTokenResponse;
import com.gusto.embedded_api.operations.GetV1TokenInfo;
import com.gusto.embedded_api.operations.RefreshAccessToken;
import com.gusto.embedded_api.utils.Headers;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;


public class AsyncIntrospection {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final Introspection syncSDK;

    AsyncIntrospection(Introspection syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public Introspection sync() {
        return syncSDK;
    }


    /**
     * Get info about the current access token
     * 
     * <p>Returns scope and resource information associated with the current access token.
     * 
     * @return The async call builder
     */
    public GetV1TokenInfoRequestBuilder getInfo() {
        return new GetV1TokenInfoRequestBuilder(sdkConfiguration);
    }

    /**
     * Get info about the current access token
     * 
     * <p>Returns scope and resource information associated with the current access token.
     * 
     * @return CompletableFuture&lt;GetV1TokenInfoResponse&gt; - The async response
     */
    public CompletableFuture<GetV1TokenInfoResponse> getInfoDirect() {
        return getInfo(Optional.empty());
    }

    /**
     * Get info about the current access token
     * 
     * <p>Returns scope and resource information associated with the current access token.
     * 
     * @param xGustoAPIVersion 
     * @return CompletableFuture&lt;GetV1TokenInfoResponse&gt; - The async response
     */
    public CompletableFuture<GetV1TokenInfoResponse> getInfo(Optional<? extends VersionHeader> xGustoAPIVersion) {
        GetV1TokenInfoRequest request =
            GetV1TokenInfoRequest
                .builder()
                .xGustoAPIVersion(xGustoAPIVersion)
                .build();
        AsyncRequestOperation<GetV1TokenInfoRequest, GetV1TokenInfoResponse> operation
              = new GetV1TokenInfo.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Refresh access token
     * 
     * <p>Exchange a refresh token for a new access token.
     * 
     * <p>The previous `refresh_token` will be revoked on the first usage of the new `access_token`.
     * 
     * <p>The `expires_in` value is provided in seconds from when the `access_token` was generated.
     * 
     * @return The async call builder
     */
    public RefreshAccessTokenRequestBuilder refreshToken() {
        return new RefreshAccessTokenRequestBuilder(sdkConfiguration);
    }

    /**
     * Refresh access token
     * 
     * <p>Exchange a refresh token for a new access token.
     * 
     * <p>The previous `refresh_token` will be revoked on the first usage of the new `access_token`.
     * 
     * <p>The `expires_in` value is provided in seconds from when the `access_token` was generated.
     * 
     * @param requestBody 
     * @return CompletableFuture&lt;RefreshAccessTokenResponse&gt; - The async response
     */
    public CompletableFuture<RefreshAccessTokenResponse> refreshToken(RefreshAccessTokenRequestBody requestBody) {
        return refreshToken(Optional.empty(), requestBody);
    }

    /**
     * Refresh access token
     * 
     * <p>Exchange a refresh token for a new access token.
     * 
     * <p>The previous `refresh_token` will be revoked on the first usage of the new `access_token`.
     * 
     * <p>The `expires_in` value is provided in seconds from when the `access_token` was generated.
     * 
     * @param xGustoAPIVersion 
     * @param requestBody 
     * @return CompletableFuture&lt;RefreshAccessTokenResponse&gt; - The async response
     */
    public CompletableFuture<RefreshAccessTokenResponse> refreshToken(Optional<? extends VersionHeader> xGustoAPIVersion, RefreshAccessTokenRequestBody requestBody) {
        RefreshAccessTokenRequest request =
            RefreshAccessTokenRequest
                .builder()
                .xGustoAPIVersion(xGustoAPIVersion)
                .requestBody(requestBody)
                .build();
        AsyncRequestOperation<RefreshAccessTokenRequest, RefreshAccessTokenResponse> operation
              = new RefreshAccessToken.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
