/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gusto.embedded_api;

import static com.gusto.embedded_api.operations.Operations.AsyncRequestOperation;

import com.gusto.embedded_api.models.components.VersionHeader;
import com.gusto.embedded_api.models.operations.GetCompaniesCompanyUuidWireInRequestUuidRequest;
import com.gusto.embedded_api.models.operations.GetWireInRequestsWireInRequestUuidRequest;
import com.gusto.embedded_api.models.operations.PutWireInRequestsWireInRequestUuidRequest;
import com.gusto.embedded_api.models.operations.PutWireInRequestsWireInRequestUuidRequestBody;
import com.gusto.embedded_api.models.operations.async.GetCompaniesCompanyUuidWireInRequestUuidRequestBuilder;
import com.gusto.embedded_api.models.operations.async.GetCompaniesCompanyUuidWireInRequestUuidResponse;
import com.gusto.embedded_api.models.operations.async.GetWireInRequestsWireInRequestUuidRequestBuilder;
import com.gusto.embedded_api.models.operations.async.GetWireInRequestsWireInRequestUuidResponse;
import com.gusto.embedded_api.models.operations.async.PutWireInRequestsWireInRequestUuidRequestBuilder;
import com.gusto.embedded_api.models.operations.async.PutWireInRequestsWireInRequestUuidResponse;
import com.gusto.embedded_api.operations.GetCompaniesCompanyUuidWireInRequestUuid;
import com.gusto.embedded_api.operations.GetWireInRequestsWireInRequestUuid;
import com.gusto.embedded_api.operations.PutWireInRequestsWireInRequestUuid;
import com.gusto.embedded_api.utils.Headers;
import java.lang.String;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;


public class AsyncWireInRequests {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final WireInRequests syncSDK;

    AsyncWireInRequests(WireInRequests syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public WireInRequests sync() {
        return syncSDK;
    }


    /**
     * Get a single Wire In Request
     * 
     * <p>Fetch a Wire In Request.
     * 
     * <p>scope: `payrolls:read`
     * 
     * @return The async call builder
     */
    public GetWireInRequestsWireInRequestUuidRequestBuilder get() {
        return new GetWireInRequestsWireInRequestUuidRequestBuilder(sdkConfiguration);
    }

    /**
     * Get a single Wire In Request
     * 
     * <p>Fetch a Wire In Request.
     * 
     * <p>scope: `payrolls:read`
     * 
     * @param wireInRequestUuid The UUID of the Wire In Request
     * @return CompletableFuture&lt;GetWireInRequestsWireInRequestUuidResponse&gt; - The async response
     */
    public CompletableFuture<GetWireInRequestsWireInRequestUuidResponse> get(String wireInRequestUuid) {
        return get(wireInRequestUuid, Optional.empty());
    }

    /**
     * Get a single Wire In Request
     * 
     * <p>Fetch a Wire In Request.
     * 
     * <p>scope: `payrolls:read`
     * 
     * @param wireInRequestUuid The UUID of the Wire In Request
     * @param xGustoAPIVersion 
     * @return CompletableFuture&lt;GetWireInRequestsWireInRequestUuidResponse&gt; - The async response
     */
    public CompletableFuture<GetWireInRequestsWireInRequestUuidResponse> get(String wireInRequestUuid, Optional<? extends VersionHeader> xGustoAPIVersion) {
        GetWireInRequestsWireInRequestUuidRequest request =
            GetWireInRequestsWireInRequestUuidRequest
                .builder()
                .wireInRequestUuid(wireInRequestUuid)
                .xGustoAPIVersion(xGustoAPIVersion)
                .build();
        AsyncRequestOperation<GetWireInRequestsWireInRequestUuidRequest, GetWireInRequestsWireInRequestUuidResponse> operation
              = new GetWireInRequestsWireInRequestUuid.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Submit a wire in request
     * 
     * <p>Submit a wire in request for a payment
     * 
     * <p>scope: `payrolls:run`
     * 
     * @return The async call builder
     */
    public PutWireInRequestsWireInRequestUuidRequestBuilder submit() {
        return new PutWireInRequestsWireInRequestUuidRequestBuilder(sdkConfiguration);
    }

    /**
     * Submit a wire in request
     * 
     * <p>Submit a wire in request for a payment
     * 
     * <p>scope: `payrolls:run`
     * 
     * @param wireInRequestUuid The UUID of the Wire In Request
     * @param requestBody 
     * @return CompletableFuture&lt;PutWireInRequestsWireInRequestUuidResponse&gt; - The async response
     */
    public CompletableFuture<PutWireInRequestsWireInRequestUuidResponse> submit(String wireInRequestUuid, PutWireInRequestsWireInRequestUuidRequestBody requestBody) {
        return submit(wireInRequestUuid, Optional.empty(), requestBody);
    }

    /**
     * Submit a wire in request
     * 
     * <p>Submit a wire in request for a payment
     * 
     * <p>scope: `payrolls:run`
     * 
     * @param wireInRequestUuid The UUID of the Wire In Request
     * @param xGustoAPIVersion 
     * @param requestBody 
     * @return CompletableFuture&lt;PutWireInRequestsWireInRequestUuidResponse&gt; - The async response
     */
    public CompletableFuture<PutWireInRequestsWireInRequestUuidResponse> submit(
            String wireInRequestUuid, Optional<? extends VersionHeader> xGustoAPIVersion,
            PutWireInRequestsWireInRequestUuidRequestBody requestBody) {
        PutWireInRequestsWireInRequestUuidRequest request =
            PutWireInRequestsWireInRequestUuidRequest
                .builder()
                .wireInRequestUuid(wireInRequestUuid)
                .xGustoAPIVersion(xGustoAPIVersion)
                .requestBody(requestBody)
                .build();
        AsyncRequestOperation<PutWireInRequestsWireInRequestUuidRequest, PutWireInRequestsWireInRequestUuidResponse> operation
              = new PutWireInRequestsWireInRequestUuid.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Get all Wire In Requests for a company
     * 
     * <p>Fetches all Wire In Requests for a company.
     * 
     * <p>scope: `payrolls:read`
     * 
     * @return The async call builder
     */
    public GetCompaniesCompanyUuidWireInRequestUuidRequestBuilder list() {
        return new GetCompaniesCompanyUuidWireInRequestUuidRequestBuilder(sdkConfiguration);
    }

    /**
     * Get all Wire In Requests for a company
     * 
     * <p>Fetches all Wire In Requests for a company.
     * 
     * <p>scope: `payrolls:read`
     * 
     * @param companyUuid The UUID of the company
     * @return CompletableFuture&lt;GetCompaniesCompanyUuidWireInRequestUuidResponse&gt; - The async response
     */
    public CompletableFuture<GetCompaniesCompanyUuidWireInRequestUuidResponse> list(String companyUuid) {
        return list(companyUuid, Optional.empty());
    }

    /**
     * Get all Wire In Requests for a company
     * 
     * <p>Fetches all Wire In Requests for a company.
     * 
     * <p>scope: `payrolls:read`
     * 
     * @param companyUuid The UUID of the company
     * @param xGustoAPIVersion 
     * @return CompletableFuture&lt;GetCompaniesCompanyUuidWireInRequestUuidResponse&gt; - The async response
     */
    public CompletableFuture<GetCompaniesCompanyUuidWireInRequestUuidResponse> list(String companyUuid, Optional<? extends VersionHeader> xGustoAPIVersion) {
        GetCompaniesCompanyUuidWireInRequestUuidRequest request =
            GetCompaniesCompanyUuidWireInRequestUuidRequest
                .builder()
                .companyUuid(companyUuid)
                .xGustoAPIVersion(xGustoAPIVersion)
                .build();
        AsyncRequestOperation<GetCompaniesCompanyUuidWireInRequestUuidRequest, GetCompaniesCompanyUuidWireInRequestUuidResponse> operation
              = new GetCompaniesCompanyUuidWireInRequestUuid.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
