/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gusto.embedded_api_v_2026_06_15.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * ReportType
 * 
 * <p>Identifies this batch item as a custom report.
 */
public enum ReportType {
    CUSTOM_REPORT("custom_report");

    @JsonValue
    private final String value;

    ReportType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<ReportType> fromValue(String value) {
        for (ReportType o: ReportType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

