/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gusto.embedded_api_v_2026_06_15.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gusto.embedded_api_v_2026_06_15.utils.Utils;
import java.lang.Override;
import java.lang.String;


public class Batch {
    /**
     * The type of entity to act on.
     */
    @JsonProperty("entity_type")
    private EntityType entityType;

    /**
     * The UUID of the payroll to cancel. Payrolls the partner is not authorized to access, or that do not
     * exist, appear in the response's `exclusions` array.
     */
    @JsonProperty("uuid")
    private String uuid;

    /**
     * The UUID of the company that owns the payroll. The partner must be mapped to this company.
     */
    @JsonProperty("company_uuid")
    private String companyUuid;

    @JsonCreator
    public Batch(
            @JsonProperty("entity_type") EntityType entityType,
            @JsonProperty("uuid") String uuid,
            @JsonProperty("company_uuid") String companyUuid) {
        Utils.checkNotNull(entityType, "entityType");
        Utils.checkNotNull(uuid, "uuid");
        Utils.checkNotNull(companyUuid, "companyUuid");
        this.entityType = entityType;
        this.uuid = uuid;
        this.companyUuid = companyUuid;
    }

    /**
     * The type of entity to act on.
     */
    @JsonIgnore
    public EntityType entityType() {
        return entityType;
    }

    /**
     * The UUID of the payroll to cancel. Payrolls the partner is not authorized to access, or that do not
     * exist, appear in the response's `exclusions` array.
     */
    @JsonIgnore
    public String uuid() {
        return uuid;
    }

    /**
     * The UUID of the company that owns the payroll. The partner must be mapped to this company.
     */
    @JsonIgnore
    public String companyUuid() {
        return companyUuid;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The type of entity to act on.
     */
    public Batch withEntityType(EntityType entityType) {
        Utils.checkNotNull(entityType, "entityType");
        this.entityType = entityType;
        return this;
    }

    /**
     * The UUID of the payroll to cancel. Payrolls the partner is not authorized to access, or that do not
     * exist, appear in the response's `exclusions` array.
     */
    public Batch withUuid(String uuid) {
        Utils.checkNotNull(uuid, "uuid");
        this.uuid = uuid;
        return this;
    }

    /**
     * The UUID of the company that owns the payroll. The partner must be mapped to this company.
     */
    public Batch withCompanyUuid(String companyUuid) {
        Utils.checkNotNull(companyUuid, "companyUuid");
        this.companyUuid = companyUuid;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Batch other = (Batch) o;
        return 
            Utils.enhancedDeepEquals(this.entityType, other.entityType) &&
            Utils.enhancedDeepEquals(this.uuid, other.uuid) &&
            Utils.enhancedDeepEquals(this.companyUuid, other.companyUuid);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            entityType, uuid, companyUuid);
    }
    
    @Override
    public String toString() {
        return Utils.toString(Batch.class,
                "entityType", entityType,
                "uuid", uuid,
                "companyUuid", companyUuid);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private EntityType entityType;

        private String uuid;

        private String companyUuid;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The type of entity to act on.
         */
        public Builder entityType(EntityType entityType) {
            Utils.checkNotNull(entityType, "entityType");
            this.entityType = entityType;
            return this;
        }


        /**
         * The UUID of the payroll to cancel. Payrolls the partner is not authorized to access, or that do not
         * exist, appear in the response's `exclusions` array.
         */
        public Builder uuid(String uuid) {
            Utils.checkNotNull(uuid, "uuid");
            this.uuid = uuid;
            return this;
        }


        /**
         * The UUID of the company that owns the payroll. The partner must be mapped to this company.
         */
        public Builder companyUuid(String companyUuid) {
            Utils.checkNotNull(companyUuid, "companyUuid");
            this.companyUuid = companyUuid;
            return this;
        }

        public Batch build() {

            return new Batch(
                entityType, uuid, companyUuid);
        }

    }
}
