/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gusto.embedded_api_v_2026_06_15.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.core.type.TypeReference;
import com.gusto.embedded_api_v_2026_06_15.utils.LazySingletonValue;
import com.gusto.embedded_api_v_2026_06_15.utils.SpeakeasyMetadata;
import com.gusto.embedded_api_v_2026_06_15.utils.Utils;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Optional;


public class GetV1EmployeesEmployeeIdJobsRequest {
    /**
     * Determines the date-based API version associated with your API call. If none is provided, your
     * application's [minimum API
     * version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=X-Gusto-API-Version")
    private Optional<? extends GetV1EmployeesEmployeeIdJobsHeaderXGustoAPIVersion> xGustoAPIVersion;

    /**
     * The UUID of the employee
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=employee_id")
    private String employeeId;

    /**
     * The page that is requested. When unspecified, will load all objects unless endpoint forces
     * pagination.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=page")
    private Optional<Long> page;

    /**
     * Number of objects per page. For majority of endpoints will default to 25
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=per")
    private Optional<Long> per;

    /**
     * Available options:
     * - all_compensations: Include all effective dated compensations for each job instead of only the
     * current compensation
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=include")
    private Optional<? extends GetV1EmployeesEmployeeIdJobsQueryParamInclude> include;

    @JsonCreator
    public GetV1EmployeesEmployeeIdJobsRequest(
            Optional<? extends GetV1EmployeesEmployeeIdJobsHeaderXGustoAPIVersion> xGustoAPIVersion,
            String employeeId,
            Optional<Long> page,
            Optional<Long> per,
            Optional<? extends GetV1EmployeesEmployeeIdJobsQueryParamInclude> include) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        Utils.checkNotNull(employeeId, "employeeId");
        Utils.checkNotNull(page, "page");
        Utils.checkNotNull(per, "per");
        Utils.checkNotNull(include, "include");
        this.xGustoAPIVersion = xGustoAPIVersion;
        this.employeeId = employeeId;
        this.page = page;
        this.per = per;
        this.include = include;
    }
    
    public GetV1EmployeesEmployeeIdJobsRequest(
            String employeeId) {
        this(Optional.empty(), employeeId, Optional.empty(),
            Optional.empty(), Optional.empty());
    }

    /**
     * Determines the date-based API version associated with your API call. If none is provided, your
     * application's [minimum API
     * version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<GetV1EmployeesEmployeeIdJobsHeaderXGustoAPIVersion> xGustoAPIVersion() {
        return (Optional<GetV1EmployeesEmployeeIdJobsHeaderXGustoAPIVersion>) xGustoAPIVersion;
    }

    /**
     * The UUID of the employee
     */
    @JsonIgnore
    public String employeeId() {
        return employeeId;
    }

    /**
     * The page that is requested. When unspecified, will load all objects unless endpoint forces
     * pagination.
     */
    @JsonIgnore
    public Optional<Long> page() {
        return page;
    }

    /**
     * Number of objects per page. For majority of endpoints will default to 25
     */
    @JsonIgnore
    public Optional<Long> per() {
        return per;
    }

    /**
     * Available options:
     * - all_compensations: Include all effective dated compensations for each job instead of only the
     * current compensation
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<GetV1EmployeesEmployeeIdJobsQueryParamInclude> include() {
        return (Optional<GetV1EmployeesEmployeeIdJobsQueryParamInclude>) include;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Determines the date-based API version associated with your API call. If none is provided, your
     * application's [minimum API
     * version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
     */
    public GetV1EmployeesEmployeeIdJobsRequest withXGustoAPIVersion(GetV1EmployeesEmployeeIdJobsHeaderXGustoAPIVersion xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = Optional.ofNullable(xGustoAPIVersion);
        return this;
    }


    /**
     * Determines the date-based API version associated with your API call. If none is provided, your
     * application's [minimum API
     * version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
     */
    public GetV1EmployeesEmployeeIdJobsRequest withXGustoAPIVersion(Optional<? extends GetV1EmployeesEmployeeIdJobsHeaderXGustoAPIVersion> xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = xGustoAPIVersion;
        return this;
    }

    /**
     * The UUID of the employee
     */
    public GetV1EmployeesEmployeeIdJobsRequest withEmployeeId(String employeeId) {
        Utils.checkNotNull(employeeId, "employeeId");
        this.employeeId = employeeId;
        return this;
    }

    /**
     * The page that is requested. When unspecified, will load all objects unless endpoint forces
     * pagination.
     */
    public GetV1EmployeesEmployeeIdJobsRequest withPage(long page) {
        Utils.checkNotNull(page, "page");
        this.page = Optional.ofNullable(page);
        return this;
    }


    /**
     * The page that is requested. When unspecified, will load all objects unless endpoint forces
     * pagination.
     */
    public GetV1EmployeesEmployeeIdJobsRequest withPage(Optional<Long> page) {
        Utils.checkNotNull(page, "page");
        this.page = page;
        return this;
    }

    /**
     * Number of objects per page. For majority of endpoints will default to 25
     */
    public GetV1EmployeesEmployeeIdJobsRequest withPer(long per) {
        Utils.checkNotNull(per, "per");
        this.per = Optional.ofNullable(per);
        return this;
    }


    /**
     * Number of objects per page. For majority of endpoints will default to 25
     */
    public GetV1EmployeesEmployeeIdJobsRequest withPer(Optional<Long> per) {
        Utils.checkNotNull(per, "per");
        this.per = per;
        return this;
    }

    /**
     * Available options:
     * - all_compensations: Include all effective dated compensations for each job instead of only the
     * current compensation
     */
    public GetV1EmployeesEmployeeIdJobsRequest withInclude(GetV1EmployeesEmployeeIdJobsQueryParamInclude include) {
        Utils.checkNotNull(include, "include");
        this.include = Optional.ofNullable(include);
        return this;
    }


    /**
     * Available options:
     * - all_compensations: Include all effective dated compensations for each job instead of only the
     * current compensation
     */
    public GetV1EmployeesEmployeeIdJobsRequest withInclude(Optional<? extends GetV1EmployeesEmployeeIdJobsQueryParamInclude> include) {
        Utils.checkNotNull(include, "include");
        this.include = include;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetV1EmployeesEmployeeIdJobsRequest other = (GetV1EmployeesEmployeeIdJobsRequest) o;
        return 
            Utils.enhancedDeepEquals(this.xGustoAPIVersion, other.xGustoAPIVersion) &&
            Utils.enhancedDeepEquals(this.employeeId, other.employeeId) &&
            Utils.enhancedDeepEquals(this.page, other.page) &&
            Utils.enhancedDeepEquals(this.per, other.per) &&
            Utils.enhancedDeepEquals(this.include, other.include);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            xGustoAPIVersion, employeeId, page,
            per, include);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetV1EmployeesEmployeeIdJobsRequest.class,
                "xGustoAPIVersion", xGustoAPIVersion,
                "employeeId", employeeId,
                "page", page,
                "per", per,
                "include", include);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<? extends GetV1EmployeesEmployeeIdJobsHeaderXGustoAPIVersion> xGustoAPIVersion;

        private String employeeId;

        private Optional<Long> page = Optional.empty();

        private Optional<Long> per = Optional.empty();

        private Optional<? extends GetV1EmployeesEmployeeIdJobsQueryParamInclude> include = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * Determines the date-based API version associated with your API call. If none is provided, your
         * application's [minimum API
         * version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
         */
        public Builder xGustoAPIVersion(GetV1EmployeesEmployeeIdJobsHeaderXGustoAPIVersion xGustoAPIVersion) {
            Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
            this.xGustoAPIVersion = Optional.ofNullable(xGustoAPIVersion);
            return this;
        }

        /**
         * Determines the date-based API version associated with your API call. If none is provided, your
         * application's [minimum API
         * version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
         */
        public Builder xGustoAPIVersion(Optional<? extends GetV1EmployeesEmployeeIdJobsHeaderXGustoAPIVersion> xGustoAPIVersion) {
            Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
            this.xGustoAPIVersion = xGustoAPIVersion;
            return this;
        }


        /**
         * The UUID of the employee
         */
        public Builder employeeId(String employeeId) {
            Utils.checkNotNull(employeeId, "employeeId");
            this.employeeId = employeeId;
            return this;
        }


        /**
         * The page that is requested. When unspecified, will load all objects unless endpoint forces
         * pagination.
         */
        public Builder page(long page) {
            Utils.checkNotNull(page, "page");
            this.page = Optional.ofNullable(page);
            return this;
        }

        /**
         * The page that is requested. When unspecified, will load all objects unless endpoint forces
         * pagination.
         */
        public Builder page(Optional<Long> page) {
            Utils.checkNotNull(page, "page");
            this.page = page;
            return this;
        }


        /**
         * Number of objects per page. For majority of endpoints will default to 25
         */
        public Builder per(long per) {
            Utils.checkNotNull(per, "per");
            this.per = Optional.ofNullable(per);
            return this;
        }

        /**
         * Number of objects per page. For majority of endpoints will default to 25
         */
        public Builder per(Optional<Long> per) {
            Utils.checkNotNull(per, "per");
            this.per = per;
            return this;
        }


        /**
         * Available options:
         * - all_compensations: Include all effective dated compensations for each job instead of only the
         * current compensation
         */
        public Builder include(GetV1EmployeesEmployeeIdJobsQueryParamInclude include) {
            Utils.checkNotNull(include, "include");
            this.include = Optional.ofNullable(include);
            return this;
        }

        /**
         * Available options:
         * - all_compensations: Include all effective dated compensations for each job instead of only the
         * current compensation
         */
        public Builder include(Optional<? extends GetV1EmployeesEmployeeIdJobsQueryParamInclude> include) {
            Utils.checkNotNull(include, "include");
            this.include = include;
            return this;
        }

        public GetV1EmployeesEmployeeIdJobsRequest build() {
            if (xGustoAPIVersion == null) {
                xGustoAPIVersion = _SINGLETON_VALUE_XGustoAPIVersion.value();
            }

            return new GetV1EmployeesEmployeeIdJobsRequest(
                xGustoAPIVersion, employeeId, page,
                per, include);
        }


        private static final LazySingletonValue<Optional<? extends GetV1EmployeesEmployeeIdJobsHeaderXGustoAPIVersion>> _SINGLETON_VALUE_XGustoAPIVersion =
                new LazySingletonValue<>(
                        "X-Gusto-API-Version",
                        "\"2026-06-15\"",
                        new TypeReference<Optional<? extends GetV1EmployeesEmployeeIdJobsHeaderXGustoAPIVersion>>() {});
    }
}
