/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gusto.embedded_api_v_2026_06_15.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gusto.embedded_api_v_2026_06_15.utils.Utils;
import java.lang.Boolean;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class PutV1CompaniesCompanyIdEarningTypesEarningTypeUuidRequestBody {
    /**
     * The name of the custom earning type.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    private Optional<String> name;

    /**
     * The earning type category. Set at creation and immutable afterward — submitting a value that differs
     * from the current one returns a 422. Submitting the current value (e.g.
     * 
     * <p>when echoing back the full resource) is allowed.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("category")
    private Optional<String> category;

    /**
     * Whether earnings of this type are included in overtime pay calculations. Set at creation and
     * immutable afterward — submitting a value that differs from the current one returns a 422. Submitting
     * the current value (e.g.
     * 
     * <p>when echoing back the full resource) is allowed.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("included_in_overtime_pay")
    private Optional<Boolean> includedInOvertimePay;

    @JsonCreator
    public PutV1CompaniesCompanyIdEarningTypesEarningTypeUuidRequestBody(
            @JsonProperty("name") Optional<String> name,
            @JsonProperty("category") Optional<String> category,
            @JsonProperty("included_in_overtime_pay") Optional<Boolean> includedInOvertimePay) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(category, "category");
        Utils.checkNotNull(includedInOvertimePay, "includedInOvertimePay");
        this.name = name;
        this.category = category;
        this.includedInOvertimePay = includedInOvertimePay;
    }
    
    public PutV1CompaniesCompanyIdEarningTypesEarningTypeUuidRequestBody() {
        this(Optional.empty(), Optional.empty(), Optional.empty());
    }

    /**
     * The name of the custom earning type.
     */
    @JsonIgnore
    public Optional<String> name() {
        return name;
    }

    /**
     * The earning type category. Set at creation and immutable afterward — submitting a value that differs
     * from the current one returns a 422. Submitting the current value (e.g.
     * 
     * <p>when echoing back the full resource) is allowed.
     */
    @JsonIgnore
    public Optional<String> category() {
        return category;
    }

    /**
     * Whether earnings of this type are included in overtime pay calculations. Set at creation and
     * immutable afterward — submitting a value that differs from the current one returns a 422. Submitting
     * the current value (e.g.
     * 
     * <p>when echoing back the full resource) is allowed.
     */
    @JsonIgnore
    public Optional<Boolean> includedInOvertimePay() {
        return includedInOvertimePay;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The name of the custom earning type.
     */
    public PutV1CompaniesCompanyIdEarningTypesEarningTypeUuidRequestBody withName(String name) {
        Utils.checkNotNull(name, "name");
        this.name = Optional.ofNullable(name);
        return this;
    }


    /**
     * The name of the custom earning type.
     */
    public PutV1CompaniesCompanyIdEarningTypesEarningTypeUuidRequestBody withName(Optional<String> name) {
        Utils.checkNotNull(name, "name");
        this.name = name;
        return this;
    }

    /**
     * The earning type category. Set at creation and immutable afterward — submitting a value that differs
     * from the current one returns a 422. Submitting the current value (e.g.
     * 
     * <p>when echoing back the full resource) is allowed.
     */
    public PutV1CompaniesCompanyIdEarningTypesEarningTypeUuidRequestBody withCategory(String category) {
        Utils.checkNotNull(category, "category");
        this.category = Optional.ofNullable(category);
        return this;
    }


    /**
     * The earning type category. Set at creation and immutable afterward — submitting a value that differs
     * from the current one returns a 422. Submitting the current value (e.g.
     * 
     * <p>when echoing back the full resource) is allowed.
     */
    public PutV1CompaniesCompanyIdEarningTypesEarningTypeUuidRequestBody withCategory(Optional<String> category) {
        Utils.checkNotNull(category, "category");
        this.category = category;
        return this;
    }

    /**
     * Whether earnings of this type are included in overtime pay calculations. Set at creation and
     * immutable afterward — submitting a value that differs from the current one returns a 422. Submitting
     * the current value (e.g.
     * 
     * <p>when echoing back the full resource) is allowed.
     */
    public PutV1CompaniesCompanyIdEarningTypesEarningTypeUuidRequestBody withIncludedInOvertimePay(boolean includedInOvertimePay) {
        Utils.checkNotNull(includedInOvertimePay, "includedInOvertimePay");
        this.includedInOvertimePay = Optional.ofNullable(includedInOvertimePay);
        return this;
    }


    /**
     * Whether earnings of this type are included in overtime pay calculations. Set at creation and
     * immutable afterward — submitting a value that differs from the current one returns a 422. Submitting
     * the current value (e.g.
     * 
     * <p>when echoing back the full resource) is allowed.
     */
    public PutV1CompaniesCompanyIdEarningTypesEarningTypeUuidRequestBody withIncludedInOvertimePay(Optional<Boolean> includedInOvertimePay) {
        Utils.checkNotNull(includedInOvertimePay, "includedInOvertimePay");
        this.includedInOvertimePay = includedInOvertimePay;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PutV1CompaniesCompanyIdEarningTypesEarningTypeUuidRequestBody other = (PutV1CompaniesCompanyIdEarningTypesEarningTypeUuidRequestBody) o;
        return 
            Utils.enhancedDeepEquals(this.name, other.name) &&
            Utils.enhancedDeepEquals(this.category, other.category) &&
            Utils.enhancedDeepEquals(this.includedInOvertimePay, other.includedInOvertimePay);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            name, category, includedInOvertimePay);
    }
    
    @Override
    public String toString() {
        return Utils.toString(PutV1CompaniesCompanyIdEarningTypesEarningTypeUuidRequestBody.class,
                "name", name,
                "category", category,
                "includedInOvertimePay", includedInOvertimePay);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<String> name = Optional.empty();

        private Optional<String> category = Optional.empty();

        private Optional<Boolean> includedInOvertimePay = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The name of the custom earning type.
         */
        public Builder name(String name) {
            Utils.checkNotNull(name, "name");
            this.name = Optional.ofNullable(name);
            return this;
        }

        /**
         * The name of the custom earning type.
         */
        public Builder name(Optional<String> name) {
            Utils.checkNotNull(name, "name");
            this.name = name;
            return this;
        }


        /**
         * The earning type category. Set at creation and immutable afterward — submitting a value that differs
         * from the current one returns a 422. Submitting the current value (e.g.
         * 
         * <p>when echoing back the full resource) is allowed.
         */
        public Builder category(String category) {
            Utils.checkNotNull(category, "category");
            this.category = Optional.ofNullable(category);
            return this;
        }

        /**
         * The earning type category. Set at creation and immutable afterward — submitting a value that differs
         * from the current one returns a 422. Submitting the current value (e.g.
         * 
         * <p>when echoing back the full resource) is allowed.
         */
        public Builder category(Optional<String> category) {
            Utils.checkNotNull(category, "category");
            this.category = category;
            return this;
        }


        /**
         * Whether earnings of this type are included in overtime pay calculations. Set at creation and
         * immutable afterward — submitting a value that differs from the current one returns a 422. Submitting
         * the current value (e.g.
         * 
         * <p>when echoing back the full resource) is allowed.
         */
        public Builder includedInOvertimePay(boolean includedInOvertimePay) {
            Utils.checkNotNull(includedInOvertimePay, "includedInOvertimePay");
            this.includedInOvertimePay = Optional.ofNullable(includedInOvertimePay);
            return this;
        }

        /**
         * Whether earnings of this type are included in overtime pay calculations. Set at creation and
         * immutable afterward — submitting a value that differs from the current one returns a 422. Submitting
         * the current value (e.g.
         * 
         * <p>when echoing back the full resource) is allowed.
         */
        public Builder includedInOvertimePay(Optional<Boolean> includedInOvertimePay) {
            Utils.checkNotNull(includedInOvertimePay, "includedInOvertimePay");
            this.includedInOvertimePay = includedInOvertimePay;
            return this;
        }

        public PutV1CompaniesCompanyIdEarningTypesEarningTypeUuidRequestBody build() {

            return new PutV1CompaniesCompanyIdEarningTypesEarningTypeUuidRequestBody(
                name, category, includedInOvertimePay);
        }

    }
}
