/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import com.fasterxml.jackson.core.type.TypeReference;
import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.operations.GetV1ContractorDocumentPdf;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.LazySingletonValue;
import org.openapis.openapi.utils.Utils;

public class GetV1ContractorDocumentPdfRequestBuilder {

    private Optional<? extends GetV1ContractorDocumentPdfHeaderXGustoAPIVersion> xGustoAPIVersion = Utils.readDefaultOrConstValue(
                            "xGustoAPIVersion",
                            "\"2025-11-15\"",
                            new TypeReference<Optional<? extends GetV1ContractorDocumentPdfHeaderXGustoAPIVersion>>() {});
    private String documentUuid;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public GetV1ContractorDocumentPdfRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }
                
    public GetV1ContractorDocumentPdfRequestBuilder xGustoAPIVersion(GetV1ContractorDocumentPdfHeaderXGustoAPIVersion xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = Optional.of(xGustoAPIVersion);
        return this;
    }

    public GetV1ContractorDocumentPdfRequestBuilder xGustoAPIVersion(Optional<? extends GetV1ContractorDocumentPdfHeaderXGustoAPIVersion> xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = xGustoAPIVersion;
        return this;
    }

    public GetV1ContractorDocumentPdfRequestBuilder documentUuid(String documentUuid) {
        Utils.checkNotNull(documentUuid, "documentUuid");
        this.documentUuid = documentUuid;
        return this;
    }


    private GetV1ContractorDocumentPdfRequest buildRequest() {
        if (xGustoAPIVersion == null) {
            xGustoAPIVersion = _SINGLETON_VALUE_XGustoAPIVersion.value();
        }

        GetV1ContractorDocumentPdfRequest request = new GetV1ContractorDocumentPdfRequest(xGustoAPIVersion,
            documentUuid);

        return request;
    }

    public GetV1ContractorDocumentPdfResponse call() {
        
        RequestOperation<GetV1ContractorDocumentPdfRequest, GetV1ContractorDocumentPdfResponse> operation
              = new GetV1ContractorDocumentPdf.Sync(sdkConfiguration, _headers);
        GetV1ContractorDocumentPdfRequest request = buildRequest();

        return operation.handleResponse(operation.doRequest(request));
    }

    private static final LazySingletonValue<Optional<? extends GetV1ContractorDocumentPdfHeaderXGustoAPIVersion>> _SINGLETON_VALUE_XGustoAPIVersion =
            new LazySingletonValue<>(
                    "xGustoAPIVersion",
                    "\"2025-11-15\"",
                    new TypeReference<Optional<? extends GetV1ContractorDocumentPdfHeaderXGustoAPIVersion>>() {});
}
