/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import com.fasterxml.jackson.core.type.TypeReference;
import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.models.components.EmployeeBenefitCreateRequest;
import org.openapis.openapi.operations.PostV1EmployeesEmployeeIdEmployeeBenefits;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.LazySingletonValue;
import org.openapis.openapi.utils.Utils;

public class PostV1EmployeesEmployeeIdEmployeeBenefitsRequestBuilder {

    private Optional<? extends PostV1EmployeesEmployeeIdEmployeeBenefitsHeaderXGustoAPIVersion> xGustoAPIVersion = Utils.readDefaultOrConstValue(
                            "xGustoAPIVersion",
                            "\"2025-11-15\"",
                            new TypeReference<Optional<? extends PostV1EmployeesEmployeeIdEmployeeBenefitsHeaderXGustoAPIVersion>>() {});
    private String employeeId;
    private EmployeeBenefitCreateRequest employeeBenefitCreateRequest;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public PostV1EmployeesEmployeeIdEmployeeBenefitsRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }
                
    public PostV1EmployeesEmployeeIdEmployeeBenefitsRequestBuilder xGustoAPIVersion(PostV1EmployeesEmployeeIdEmployeeBenefitsHeaderXGustoAPIVersion xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = Optional.of(xGustoAPIVersion);
        return this;
    }

    public PostV1EmployeesEmployeeIdEmployeeBenefitsRequestBuilder xGustoAPIVersion(Optional<? extends PostV1EmployeesEmployeeIdEmployeeBenefitsHeaderXGustoAPIVersion> xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = xGustoAPIVersion;
        return this;
    }

    public PostV1EmployeesEmployeeIdEmployeeBenefitsRequestBuilder employeeId(String employeeId) {
        Utils.checkNotNull(employeeId, "employeeId");
        this.employeeId = employeeId;
        return this;
    }

    public PostV1EmployeesEmployeeIdEmployeeBenefitsRequestBuilder employeeBenefitCreateRequest(EmployeeBenefitCreateRequest employeeBenefitCreateRequest) {
        Utils.checkNotNull(employeeBenefitCreateRequest, "employeeBenefitCreateRequest");
        this.employeeBenefitCreateRequest = employeeBenefitCreateRequest;
        return this;
    }


    private PostV1EmployeesEmployeeIdEmployeeBenefitsRequest buildRequest() {
        if (xGustoAPIVersion == null) {
            xGustoAPIVersion = _SINGLETON_VALUE_XGustoAPIVersion.value();
        }

        PostV1EmployeesEmployeeIdEmployeeBenefitsRequest request = new PostV1EmployeesEmployeeIdEmployeeBenefitsRequest(xGustoAPIVersion,
            employeeId,
            employeeBenefitCreateRequest);

        return request;
    }

    public PostV1EmployeesEmployeeIdEmployeeBenefitsResponse call() {
        
        RequestOperation<PostV1EmployeesEmployeeIdEmployeeBenefitsRequest, PostV1EmployeesEmployeeIdEmployeeBenefitsResponse> operation
              = new PostV1EmployeesEmployeeIdEmployeeBenefits.Sync(sdkConfiguration, _headers);
        PostV1EmployeesEmployeeIdEmployeeBenefitsRequest request = buildRequest();

        return operation.handleResponse(operation.doRequest(request));
    }

    private static final LazySingletonValue<Optional<? extends PostV1EmployeesEmployeeIdEmployeeBenefitsHeaderXGustoAPIVersion>> _SINGLETON_VALUE_XGustoAPIVersion =
            new LazySingletonValue<>(
                    "xGustoAPIVersion",
                    "\"2025-11-15\"",
                    new TypeReference<Optional<? extends PostV1EmployeesEmployeeIdEmployeeBenefitsHeaderXGustoAPIVersion>>() {});
}
