/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import com.fasterxml.jackson.core.type.TypeReference;
import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.operations.PutV1RecurringReimbursements;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.LazySingletonValue;
import org.openapis.openapi.utils.Utils;

public class PutV1RecurringReimbursementsRequestBuilder {

    private Optional<? extends PutV1RecurringReimbursementsHeaderXGustoAPIVersion> xGustoAPIVersion = Utils.readDefaultOrConstValue(
                            "xGustoAPIVersion",
                            "\"2025-11-15\"",
                            new TypeReference<Optional<? extends PutV1RecurringReimbursementsHeaderXGustoAPIVersion>>() {});
    private String id;
    private PutV1RecurringReimbursementsRequestBody requestBody;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public PutV1RecurringReimbursementsRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }
                
    public PutV1RecurringReimbursementsRequestBuilder xGustoAPIVersion(PutV1RecurringReimbursementsHeaderXGustoAPIVersion xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = Optional.of(xGustoAPIVersion);
        return this;
    }

    public PutV1RecurringReimbursementsRequestBuilder xGustoAPIVersion(Optional<? extends PutV1RecurringReimbursementsHeaderXGustoAPIVersion> xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = xGustoAPIVersion;
        return this;
    }

    public PutV1RecurringReimbursementsRequestBuilder id(String id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }

    public PutV1RecurringReimbursementsRequestBuilder requestBody(PutV1RecurringReimbursementsRequestBody requestBody) {
        Utils.checkNotNull(requestBody, "requestBody");
        this.requestBody = requestBody;
        return this;
    }


    private PutV1RecurringReimbursementsRequest buildRequest() {
        if (xGustoAPIVersion == null) {
            xGustoAPIVersion = _SINGLETON_VALUE_XGustoAPIVersion.value();
        }

        PutV1RecurringReimbursementsRequest request = new PutV1RecurringReimbursementsRequest(xGustoAPIVersion,
            id,
            requestBody);

        return request;
    }

    public PutV1RecurringReimbursementsResponse call() {
        
        RequestOperation<PutV1RecurringReimbursementsRequest, PutV1RecurringReimbursementsResponse> operation
              = new PutV1RecurringReimbursements.Sync(sdkConfiguration, _headers);
        PutV1RecurringReimbursementsRequest request = buildRequest();

        return operation.handleResponse(operation.doRequest(request));
    }

    private static final LazySingletonValue<Optional<? extends PutV1RecurringReimbursementsHeaderXGustoAPIVersion>> _SINGLETON_VALUE_XGustoAPIVersion =
            new LazySingletonValue<>(
                    "xGustoAPIVersion",
                    "\"2025-11-15\"",
                    new TypeReference<Optional<? extends PutV1RecurringReimbursementsHeaderXGustoAPIVersion>>() {});
}
