/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import com.fasterxml.jackson.core.type.TypeReference;
import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.operations.PutV1TaxLiabilitiesFinish;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.LazySingletonValue;
import org.openapis.openapi.utils.Utils;

public class PutV1TaxLiabilitiesFinishRequestBuilder {

    private Optional<? extends PutV1TaxLiabilitiesFinishHeaderXGustoAPIVersion> xGustoAPIVersion = Utils.readDefaultOrConstValue(
                            "xGustoAPIVersion",
                            "\"2025-11-15\"",
                            new TypeReference<Optional<? extends PutV1TaxLiabilitiesFinishHeaderXGustoAPIVersion>>() {});
    private String companyUuid;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public PutV1TaxLiabilitiesFinishRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }
                
    public PutV1TaxLiabilitiesFinishRequestBuilder xGustoAPIVersion(PutV1TaxLiabilitiesFinishHeaderXGustoAPIVersion xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = Optional.of(xGustoAPIVersion);
        return this;
    }

    public PutV1TaxLiabilitiesFinishRequestBuilder xGustoAPIVersion(Optional<? extends PutV1TaxLiabilitiesFinishHeaderXGustoAPIVersion> xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = xGustoAPIVersion;
        return this;
    }

    public PutV1TaxLiabilitiesFinishRequestBuilder companyUuid(String companyUuid) {
        Utils.checkNotNull(companyUuid, "companyUuid");
        this.companyUuid = companyUuid;
        return this;
    }


    private PutV1TaxLiabilitiesFinishRequest buildRequest() {
        if (xGustoAPIVersion == null) {
            xGustoAPIVersion = _SINGLETON_VALUE_XGustoAPIVersion.value();
        }

        PutV1TaxLiabilitiesFinishRequest request = new PutV1TaxLiabilitiesFinishRequest(xGustoAPIVersion,
            companyUuid);

        return request;
    }

    public PutV1TaxLiabilitiesFinishResponse call() {
        
        RequestOperation<PutV1TaxLiabilitiesFinishRequest, PutV1TaxLiabilitiesFinishResponse> operation
              = new PutV1TaxLiabilitiesFinish.Sync(sdkConfiguration, _headers);
        PutV1TaxLiabilitiesFinishRequest request = buildRequest();

        return operation.handleResponse(operation.doRequest(request));
    }

    private static final LazySingletonValue<Optional<? extends PutV1TaxLiabilitiesFinishHeaderXGustoAPIVersion>> _SINGLETON_VALUE_XGustoAPIVersion =
            new LazySingletonValue<>(
                    "xGustoAPIVersion",
                    "\"2025-11-15\"",
                    new TypeReference<Optional<? extends PutV1TaxLiabilitiesFinishHeaderXGustoAPIVersion>>() {});
}
