/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gusto.embedded_api.models.operations;

import com.fasterxml.jackson.core.type.TypeReference;
import com.gusto.embedded_api.utils.LazySingletonValue;
import com.gusto.embedded_api.utils.Utils;
import java.lang.Exception;
import java.lang.String;
import java.util.Optional;

public class DeleteV1HomeAddressesHomeAddressUuidRequestBuilder {

    private Optional<? extends DeleteV1HomeAddressesHomeAddressUuidHeaderXGustoAPIVersion> xGustoAPIVersion = Utils.readDefaultOrConstValue(
                            "xGustoAPIVersion",
                            "\"2024-04-01\"",
                            new TypeReference<Optional<? extends DeleteV1HomeAddressesHomeAddressUuidHeaderXGustoAPIVersion>>() {});
    private String homeAddressUuid;
    private final SDKMethodInterfaces.MethodCallDeleteV1HomeAddressesHomeAddressUuid sdk;

    public DeleteV1HomeAddressesHomeAddressUuidRequestBuilder(SDKMethodInterfaces.MethodCallDeleteV1HomeAddressesHomeAddressUuid sdk) {
        this.sdk = sdk;
    }
                
    public DeleteV1HomeAddressesHomeAddressUuidRequestBuilder xGustoAPIVersion(DeleteV1HomeAddressesHomeAddressUuidHeaderXGustoAPIVersion xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = Optional.of(xGustoAPIVersion);
        return this;
    }

    public DeleteV1HomeAddressesHomeAddressUuidRequestBuilder xGustoAPIVersion(Optional<? extends DeleteV1HomeAddressesHomeAddressUuidHeaderXGustoAPIVersion> xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = xGustoAPIVersion;
        return this;
    }

    public DeleteV1HomeAddressesHomeAddressUuidRequestBuilder homeAddressUuid(String homeAddressUuid) {
        Utils.checkNotNull(homeAddressUuid, "homeAddressUuid");
        this.homeAddressUuid = homeAddressUuid;
        return this;
    }

    public DeleteV1HomeAddressesHomeAddressUuidResponse call() throws Exception {
        if (xGustoAPIVersion == null) {
            xGustoAPIVersion = _SINGLETON_VALUE_XGustoAPIVersion.value();
        }
        return sdk.delete(
            xGustoAPIVersion,
            homeAddressUuid);
    }

    private static final LazySingletonValue<Optional<? extends DeleteV1HomeAddressesHomeAddressUuidHeaderXGustoAPIVersion>> _SINGLETON_VALUE_XGustoAPIVersion =
            new LazySingletonValue<>(
                    "xGustoAPIVersion",
                    "\"2024-04-01\"",
                    new TypeReference<Optional<? extends DeleteV1HomeAddressesHomeAddressUuidHeaderXGustoAPIVersion>>() {});
}
