/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.gusto.embedded_api.models.operations;

import com.gusto.embedded_api.models.components.VersionHeader;
import com.gusto.embedded_api.utils.Utils;
import java.lang.Double;
import java.lang.String;
import java.util.Optional;

public class GetV1CompanyBenefitsCompanyBenefitIdEmployeeBenefitsRequestBuilder {

    private String companyBenefitId;
    private Optional<Double> page = Optional.empty();
    private Optional<Double> per = Optional.empty();
    private Optional<? extends VersionHeader> xGustoAPIVersion = Optional.empty();
    private final SDKMethodInterfaces.MethodCallGetV1CompanyBenefitsCompanyBenefitIdEmployeeBenefits sdk;

    public GetV1CompanyBenefitsCompanyBenefitIdEmployeeBenefitsRequestBuilder(SDKMethodInterfaces.MethodCallGetV1CompanyBenefitsCompanyBenefitIdEmployeeBenefits sdk) {
        this.sdk = sdk;
    }

    public GetV1CompanyBenefitsCompanyBenefitIdEmployeeBenefitsRequestBuilder companyBenefitId(String companyBenefitId) {
        Utils.checkNotNull(companyBenefitId, "companyBenefitId");
        this.companyBenefitId = companyBenefitId;
        return this;
    }
                
    public GetV1CompanyBenefitsCompanyBenefitIdEmployeeBenefitsRequestBuilder page(double page) {
        Utils.checkNotNull(page, "page");
        this.page = Optional.of(page);
        return this;
    }

    public GetV1CompanyBenefitsCompanyBenefitIdEmployeeBenefitsRequestBuilder page(Optional<Double> page) {
        Utils.checkNotNull(page, "page");
        this.page = page;
        return this;
    }
                
    public GetV1CompanyBenefitsCompanyBenefitIdEmployeeBenefitsRequestBuilder per(double per) {
        Utils.checkNotNull(per, "per");
        this.per = Optional.of(per);
        return this;
    }

    public GetV1CompanyBenefitsCompanyBenefitIdEmployeeBenefitsRequestBuilder per(Optional<Double> per) {
        Utils.checkNotNull(per, "per");
        this.per = per;
        return this;
    }
                
    public GetV1CompanyBenefitsCompanyBenefitIdEmployeeBenefitsRequestBuilder xGustoAPIVersion(VersionHeader xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = Optional.of(xGustoAPIVersion);
        return this;
    }

    public GetV1CompanyBenefitsCompanyBenefitIdEmployeeBenefitsRequestBuilder xGustoAPIVersion(Optional<? extends VersionHeader> xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = xGustoAPIVersion;
        return this;
    }

    public GetV1CompanyBenefitsCompanyBenefitIdEmployeeBenefitsResponse call() throws Exception {

        return sdk.getEmployeeBenefits(
            companyBenefitId,
            page,
            per,
            xGustoAPIVersion);
    }
}
