/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.gusto.embedded_api.models.operations;

import com.gusto.embedded_api.models.components.HistoricalEmployeeBody;
import com.gusto.embedded_api.models.components.VersionHeader;
import com.gusto.embedded_api.utils.Utils;
import java.lang.String;
import java.util.Optional;

public class PostV1HistoricalEmployeesRequestBuilder {

    private String companyUuid;
    private Optional<? extends VersionHeader> xGustoAPIVersion = Optional.empty();
    private HistoricalEmployeeBody historicalEmployeeBody;
    private final SDKMethodInterfaces.MethodCallPostV1HistoricalEmployees sdk;

    public PostV1HistoricalEmployeesRequestBuilder(SDKMethodInterfaces.MethodCallPostV1HistoricalEmployees sdk) {
        this.sdk = sdk;
    }

    public PostV1HistoricalEmployeesRequestBuilder companyUuid(String companyUuid) {
        Utils.checkNotNull(companyUuid, "companyUuid");
        this.companyUuid = companyUuid;
        return this;
    }
                
    public PostV1HistoricalEmployeesRequestBuilder xGustoAPIVersion(VersionHeader xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = Optional.of(xGustoAPIVersion);
        return this;
    }

    public PostV1HistoricalEmployeesRequestBuilder xGustoAPIVersion(Optional<? extends VersionHeader> xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = xGustoAPIVersion;
        return this;
    }

    public PostV1HistoricalEmployeesRequestBuilder historicalEmployeeBody(HistoricalEmployeeBody historicalEmployeeBody) {
        Utils.checkNotNull(historicalEmployeeBody, "historicalEmployeeBody");
        this.historicalEmployeeBody = historicalEmployeeBody;
        return this;
    }

    public PostV1HistoricalEmployeesResponse call() throws Exception {

        return sdk.createHistorical(
            companyUuid,
            xGustoAPIVersion,
            historicalEmployeeBody);
    }
}
