/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.gusto.embedded_api.models.operations;

import com.gusto.embedded_api.models.components.VersionHeader;
import com.gusto.embedded_api.utils.Utils;
import java.lang.String;
import java.util.Optional;

public class PostV1CompaniesCompanyIdBankAccountsRequestBuilder {

    private String companyId;
    private Optional<? extends VersionHeader> xGustoAPIVersion = Optional.empty();
    private PostV1CompaniesCompanyIdBankAccountsRequestBody requestBody;
    private final SDKMethodInterfaces.MethodCallPostV1CompaniesCompanyIdBankAccounts sdk;

    public PostV1CompaniesCompanyIdBankAccountsRequestBuilder(SDKMethodInterfaces.MethodCallPostV1CompaniesCompanyIdBankAccounts sdk) {
        this.sdk = sdk;
    }

    public PostV1CompaniesCompanyIdBankAccountsRequestBuilder companyId(String companyId) {
        Utils.checkNotNull(companyId, "companyId");
        this.companyId = companyId;
        return this;
    }
                
    public PostV1CompaniesCompanyIdBankAccountsRequestBuilder xGustoAPIVersion(VersionHeader xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = Optional.of(xGustoAPIVersion);
        return this;
    }

    public PostV1CompaniesCompanyIdBankAccountsRequestBuilder xGustoAPIVersion(Optional<? extends VersionHeader> xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = xGustoAPIVersion;
        return this;
    }

    public PostV1CompaniesCompanyIdBankAccountsRequestBuilder requestBody(PostV1CompaniesCompanyIdBankAccountsRequestBody requestBody) {
        Utils.checkNotNull(requestBody, "requestBody");
        this.requestBody = requestBody;
        return this;
    }

    public PostV1CompaniesCompanyIdBankAccountsResponse call() throws Exception {

        return sdk.create(
            companyId,
            xGustoAPIVersion,
            requestBody);
    }
}
