/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.gusto.embedded_api.models.operations;

import com.gusto.embedded_api.models.components.VersionHeader;
import com.gusto.embedded_api.utils.Utils;
import java.lang.String;
import java.util.Optional;

public class PutDepartmentsRequestBuilder {

    private String departmentUuid;
    private Optional<? extends VersionHeader> xGustoAPIVersion = Optional.empty();
    private PutDepartmentsRequestBody requestBody;
    private final SDKMethodInterfaces.MethodCallPutDepartments sdk;

    public PutDepartmentsRequestBuilder(SDKMethodInterfaces.MethodCallPutDepartments sdk) {
        this.sdk = sdk;
    }

    public PutDepartmentsRequestBuilder departmentUuid(String departmentUuid) {
        Utils.checkNotNull(departmentUuid, "departmentUuid");
        this.departmentUuid = departmentUuid;
        return this;
    }
                
    public PutDepartmentsRequestBuilder xGustoAPIVersion(VersionHeader xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = Optional.of(xGustoAPIVersion);
        return this;
    }

    public PutDepartmentsRequestBuilder xGustoAPIVersion(Optional<? extends VersionHeader> xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = xGustoAPIVersion;
        return this;
    }

    public PutDepartmentsRequestBuilder requestBody(PutDepartmentsRequestBody requestBody) {
        Utils.checkNotNull(requestBody, "requestBody");
        this.requestBody = requestBody;
        return this;
    }

    public PutDepartmentsResponse call() throws Exception {

        return sdk.update(
            departmentUuid,
            xGustoAPIVersion,
            requestBody);
    }
}
