/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.gusto.embedded_api.models.operations;

import com.gusto.embedded_api.models.components.VersionHeader;
import com.gusto.embedded_api.utils.Utils;
import java.lang.String;
import java.util.Optional;

public class PutV1EmployeesEmployeeIdBankAccountsRequestBuilder {

    private String employeeId;
    private String bankAccountUuid;
    private Optional<? extends VersionHeader> xGustoAPIVersion = Optional.empty();
    private PutV1EmployeesEmployeeIdBankAccountsRequestBody requestBody;
    private final SDKMethodInterfaces.MethodCallPutV1EmployeesEmployeeIdBankAccounts sdk;

    public PutV1EmployeesEmployeeIdBankAccountsRequestBuilder(SDKMethodInterfaces.MethodCallPutV1EmployeesEmployeeIdBankAccounts sdk) {
        this.sdk = sdk;
    }

    public PutV1EmployeesEmployeeIdBankAccountsRequestBuilder employeeId(String employeeId) {
        Utils.checkNotNull(employeeId, "employeeId");
        this.employeeId = employeeId;
        return this;
    }

    public PutV1EmployeesEmployeeIdBankAccountsRequestBuilder bankAccountUuid(String bankAccountUuid) {
        Utils.checkNotNull(bankAccountUuid, "bankAccountUuid");
        this.bankAccountUuid = bankAccountUuid;
        return this;
    }
                
    public PutV1EmployeesEmployeeIdBankAccountsRequestBuilder xGustoAPIVersion(VersionHeader xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = Optional.of(xGustoAPIVersion);
        return this;
    }

    public PutV1EmployeesEmployeeIdBankAccountsRequestBuilder xGustoAPIVersion(Optional<? extends VersionHeader> xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = xGustoAPIVersion;
        return this;
    }

    public PutV1EmployeesEmployeeIdBankAccountsRequestBuilder requestBody(PutV1EmployeesEmployeeIdBankAccountsRequestBody requestBody) {
        Utils.checkNotNull(requestBody, "requestBody");
        this.requestBody = requestBody;
        return this;
    }

    public PutV1EmployeesEmployeeIdBankAccountsResponse call() throws Exception {

        return sdk.updateBankAccount(
            employeeId,
            bankAccountUuid,
            xGustoAPIVersion,
            requestBody);
    }
}
