/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */


package com.gusto.embedded_api.models.operations;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
/**
 * PutV1CompaniesCompanyIdPayrollsWithholdingPayPeriod
 * 
 * <p>The payment schedule tax rate the payroll is based on. Only relevant for off-cycle payrolls.
 */
public enum PutV1CompaniesCompanyIdPayrollsWithholdingPayPeriod {
    EVERY_WEEK("Every week"),
    EVERY_OTHER_WEEK("Every other week"),
    TWICE_PER_MONTH("Twice per month"),
    MONTHLY("Monthly"),
    QUARTERLY("Quarterly"),
    SEMIANNUALLY("Semiannually"),
    ANNUALLY("Annually");

    @JsonValue
    private final String value;

    private PutV1CompaniesCompanyIdPayrollsWithholdingPayPeriod(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<PutV1CompaniesCompanyIdPayrollsWithholdingPayPeriod> fromValue(String value) {
        for (PutV1CompaniesCompanyIdPayrollsWithholdingPayPeriod o: PutV1CompaniesCompanyIdPayrollsWithholdingPayPeriod.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}
