/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gusto.embedded_api.models.operations;

import static com.gusto.embedded_api.operations.Operations.RequestOperation;

import com.fasterxml.jackson.core.type.TypeReference;
import com.gusto.embedded_api.SDKConfiguration;
import com.gusto.embedded_api.models.components.VersionHeader;
import com.gusto.embedded_api.operations.PutV1CompaniesCompanyUuidSignatoriesSignatoryUuid;
import com.gusto.embedded_api.utils.Headers;
import com.gusto.embedded_api.utils.LazySingletonValue;
import com.gusto.embedded_api.utils.Utils;
import java.lang.Exception;
import java.lang.String;
import java.util.Optional;

public class PutV1CompaniesCompanyUuidSignatoriesSignatoryUuidRequestBuilder {

    private String companyUuid;
    private String signatoryUuid;
    private Optional<? extends VersionHeader> xGustoAPIVersion = Utils.readDefaultOrConstValue(
                            "xGustoAPIVersion",
                            "\"2024-04-01\"",
                            new TypeReference<Optional<? extends VersionHeader>>() {});
    private PutV1CompaniesCompanyUuidSignatoriesSignatoryUuidRequestBody requestBody;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public PutV1CompaniesCompanyUuidSignatoriesSignatoryUuidRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public PutV1CompaniesCompanyUuidSignatoriesSignatoryUuidRequestBuilder companyUuid(String companyUuid) {
        Utils.checkNotNull(companyUuid, "companyUuid");
        this.companyUuid = companyUuid;
        return this;
    }

    public PutV1CompaniesCompanyUuidSignatoriesSignatoryUuidRequestBuilder signatoryUuid(String signatoryUuid) {
        Utils.checkNotNull(signatoryUuid, "signatoryUuid");
        this.signatoryUuid = signatoryUuid;
        return this;
    }
                
    public PutV1CompaniesCompanyUuidSignatoriesSignatoryUuidRequestBuilder xGustoAPIVersion(VersionHeader xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = Optional.of(xGustoAPIVersion);
        return this;
    }

    public PutV1CompaniesCompanyUuidSignatoriesSignatoryUuidRequestBuilder xGustoAPIVersion(Optional<? extends VersionHeader> xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = xGustoAPIVersion;
        return this;
    }

    public PutV1CompaniesCompanyUuidSignatoriesSignatoryUuidRequestBuilder requestBody(PutV1CompaniesCompanyUuidSignatoriesSignatoryUuidRequestBody requestBody) {
        Utils.checkNotNull(requestBody, "requestBody");
        this.requestBody = requestBody;
        return this;
    }


    private PutV1CompaniesCompanyUuidSignatoriesSignatoryUuidRequest buildRequest() {
        if (xGustoAPIVersion == null) {
            xGustoAPIVersion = _SINGLETON_VALUE_XGustoAPIVersion.value();
        }

        PutV1CompaniesCompanyUuidSignatoriesSignatoryUuidRequest request = new PutV1CompaniesCompanyUuidSignatoriesSignatoryUuidRequest(companyUuid,
            signatoryUuid,
            xGustoAPIVersion,
            requestBody);

        return request;
    }

    public PutV1CompaniesCompanyUuidSignatoriesSignatoryUuidResponse call() throws Exception {
        
        RequestOperation<PutV1CompaniesCompanyUuidSignatoriesSignatoryUuidRequest, PutV1CompaniesCompanyUuidSignatoriesSignatoryUuidResponse> operation
              = new PutV1CompaniesCompanyUuidSignatoriesSignatoryUuid.Sync(sdkConfiguration, _headers);
        PutV1CompaniesCompanyUuidSignatoriesSignatoryUuidRequest request = buildRequest();

        return operation.handleResponse(operation.doRequest(request));
    }

    private static final LazySingletonValue<Optional<? extends VersionHeader>> _SINGLETON_VALUE_XGustoAPIVersion =
            new LazySingletonValue<>(
                    "xGustoAPIVersion",
                    "\"2024-04-01\"",
                    new TypeReference<Optional<? extends VersionHeader>>() {});
}
