/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.gusto.embedded_api.models.operations;

import com.gusto.embedded_api.models.components.VersionHeader;
import com.gusto.embedded_api.utils.Utils;
import java.lang.String;
import java.util.Optional;

public class PutV1CompaniesCompanyIdPayrollsRequestBuilder {

    private String companyId;
    private String payrollId;
    private Optional<? extends VersionHeader> xGustoAPIVersion = Optional.empty();
    private PutV1CompaniesCompanyIdPayrollsRequestBody requestBody;
    private final SDKMethodInterfaces.MethodCallPutV1CompaniesCompanyIdPayrolls sdk;

    public PutV1CompaniesCompanyIdPayrollsRequestBuilder(SDKMethodInterfaces.MethodCallPutV1CompaniesCompanyIdPayrolls sdk) {
        this.sdk = sdk;
    }

    public PutV1CompaniesCompanyIdPayrollsRequestBuilder companyId(String companyId) {
        Utils.checkNotNull(companyId, "companyId");
        this.companyId = companyId;
        return this;
    }

    public PutV1CompaniesCompanyIdPayrollsRequestBuilder payrollId(String payrollId) {
        Utils.checkNotNull(payrollId, "payrollId");
        this.payrollId = payrollId;
        return this;
    }
                
    public PutV1CompaniesCompanyIdPayrollsRequestBuilder xGustoAPIVersion(VersionHeader xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = Optional.of(xGustoAPIVersion);
        return this;
    }

    public PutV1CompaniesCompanyIdPayrollsRequestBuilder xGustoAPIVersion(Optional<? extends VersionHeader> xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = xGustoAPIVersion;
        return this;
    }

    public PutV1CompaniesCompanyIdPayrollsRequestBuilder requestBody(PutV1CompaniesCompanyIdPayrollsRequestBody requestBody) {
        Utils.checkNotNull(requestBody, "requestBody");
        this.requestBody = requestBody;
        return this;
    }

    public PutV1CompaniesCompanyIdPayrollsResponse call() throws Exception {

        return sdk.update(
            companyId,
            payrollId,
            xGustoAPIVersion,
            requestBody);
    }
}
