/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */


package com.gusto.embedded_api.models.operations;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.gusto.embedded_api.models.components.VersionHeader;
import com.gusto.embedded_api.utils.SpeakeasyMetadata;
import com.gusto.embedded_api.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Objects;
import java.util.Optional;

public class PutV1VerifyWebhookSubscriptionUuidRequest {

    /**
     * The webhook subscription UUID.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=webhook_subscription_uuid")
    private String webhookSubscriptionUuid;

    /**
     * Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=X-Gusto-API-Version")
    private Optional<? extends VersionHeader> xGustoAPIVersion;

    @SpeakeasyMetadata("request:mediaType=application/json")
    private PutV1VerifyWebhookSubscriptionUuidRequestBody requestBody;

    @JsonCreator
    public PutV1VerifyWebhookSubscriptionUuidRequest(
            String webhookSubscriptionUuid,
            Optional<? extends VersionHeader> xGustoAPIVersion,
            PutV1VerifyWebhookSubscriptionUuidRequestBody requestBody) {
        Utils.checkNotNull(webhookSubscriptionUuid, "webhookSubscriptionUuid");
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        Utils.checkNotNull(requestBody, "requestBody");
        this.webhookSubscriptionUuid = webhookSubscriptionUuid;
        this.xGustoAPIVersion = xGustoAPIVersion;
        this.requestBody = requestBody;
    }
    
    public PutV1VerifyWebhookSubscriptionUuidRequest(
            String webhookSubscriptionUuid,
            PutV1VerifyWebhookSubscriptionUuidRequestBody requestBody) {
        this(webhookSubscriptionUuid, Optional.empty(), requestBody);
    }

    /**
     * The webhook subscription UUID.
     */
    @JsonIgnore
    public String webhookSubscriptionUuid() {
        return webhookSubscriptionUuid;
    }

    /**
     * Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<VersionHeader> xGustoAPIVersion() {
        return (Optional<VersionHeader>) xGustoAPIVersion;
    }

    @JsonIgnore
    public PutV1VerifyWebhookSubscriptionUuidRequestBody requestBody() {
        return requestBody;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * The webhook subscription UUID.
     */
    public PutV1VerifyWebhookSubscriptionUuidRequest withWebhookSubscriptionUuid(String webhookSubscriptionUuid) {
        Utils.checkNotNull(webhookSubscriptionUuid, "webhookSubscriptionUuid");
        this.webhookSubscriptionUuid = webhookSubscriptionUuid;
        return this;
    }

    /**
     * Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
     */
    public PutV1VerifyWebhookSubscriptionUuidRequest withXGustoAPIVersion(VersionHeader xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = Optional.ofNullable(xGustoAPIVersion);
        return this;
    }

    /**
     * Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
     */
    public PutV1VerifyWebhookSubscriptionUuidRequest withXGustoAPIVersion(Optional<? extends VersionHeader> xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = xGustoAPIVersion;
        return this;
    }

    public PutV1VerifyWebhookSubscriptionUuidRequest withRequestBody(PutV1VerifyWebhookSubscriptionUuidRequestBody requestBody) {
        Utils.checkNotNull(requestBody, "requestBody");
        this.requestBody = requestBody;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PutV1VerifyWebhookSubscriptionUuidRequest other = (PutV1VerifyWebhookSubscriptionUuidRequest) o;
        return 
            Objects.deepEquals(this.webhookSubscriptionUuid, other.webhookSubscriptionUuid) &&
            Objects.deepEquals(this.xGustoAPIVersion, other.xGustoAPIVersion) &&
            Objects.deepEquals(this.requestBody, other.requestBody);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            webhookSubscriptionUuid,
            xGustoAPIVersion,
            requestBody);
    }
    
    @Override
    public String toString() {
        return Utils.toString(PutV1VerifyWebhookSubscriptionUuidRequest.class,
                "webhookSubscriptionUuid", webhookSubscriptionUuid,
                "xGustoAPIVersion", xGustoAPIVersion,
                "requestBody", requestBody);
    }
    
    public final static class Builder {
 
        private String webhookSubscriptionUuid;
 
        private Optional<? extends VersionHeader> xGustoAPIVersion = Optional.empty();
 
        private PutV1VerifyWebhookSubscriptionUuidRequestBody requestBody;  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * The webhook subscription UUID.
         */
        public Builder webhookSubscriptionUuid(String webhookSubscriptionUuid) {
            Utils.checkNotNull(webhookSubscriptionUuid, "webhookSubscriptionUuid");
            this.webhookSubscriptionUuid = webhookSubscriptionUuid;
            return this;
        }

        /**
         * Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
         */
        public Builder xGustoAPIVersion(VersionHeader xGustoAPIVersion) {
            Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
            this.xGustoAPIVersion = Optional.ofNullable(xGustoAPIVersion);
            return this;
        }

        /**
         * Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
         */
        public Builder xGustoAPIVersion(Optional<? extends VersionHeader> xGustoAPIVersion) {
            Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
            this.xGustoAPIVersion = xGustoAPIVersion;
            return this;
        }

        public Builder requestBody(PutV1VerifyWebhookSubscriptionUuidRequestBody requestBody) {
            Utils.checkNotNull(requestBody, "requestBody");
            this.requestBody = requestBody;
            return this;
        }
        
        public PutV1VerifyWebhookSubscriptionUuidRequest build() {
            return new PutV1VerifyWebhookSubscriptionUuidRequest(
                webhookSubscriptionUuid,
                xGustoAPIVersion,
                requestBody);
        }
    }
}

