/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.gusto.embedded_api.models.operations;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gusto.embedded_api.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Objects;
import java.util.Optional;


public class PutV1CompanyIndustryRequestBody {

    /**
     * Industry title
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("title")
    private Optional<String> title;

    /**
     * North American Industry Classification System (NAICS) is used to classify businesses with a six digit number based on the primary type of work the business performs
     */
    @JsonProperty("naics_code")
    private String naicsCode;

    /**
     * A list of Standard Industrial Classification (SIC) codes, which are four digit number that categorize the industries that companies belong to based on their business activities. If sic_codes is not passed in, we will perform an internal lookup with naics_code.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("sic_codes")
    private Optional<? extends List<String>> sicCodes;

    @JsonCreator
    public PutV1CompanyIndustryRequestBody(
            @JsonProperty("title") Optional<String> title,
            @JsonProperty("naics_code") String naicsCode,
            @JsonProperty("sic_codes") Optional<? extends List<String>> sicCodes) {
        Utils.checkNotNull(title, "title");
        Utils.checkNotNull(naicsCode, "naicsCode");
        Utils.checkNotNull(sicCodes, "sicCodes");
        this.title = title;
        this.naicsCode = naicsCode;
        this.sicCodes = sicCodes;
    }
    
    public PutV1CompanyIndustryRequestBody(
            String naicsCode) {
        this(Optional.empty(), naicsCode, Optional.empty());
    }

    /**
     * Industry title
     */
    @JsonIgnore
    public Optional<String> title() {
        return title;
    }

    /**
     * North American Industry Classification System (NAICS) is used to classify businesses with a six digit number based on the primary type of work the business performs
     */
    @JsonIgnore
    public String naicsCode() {
        return naicsCode;
    }

    /**
     * A list of Standard Industrial Classification (SIC) codes, which are four digit number that categorize the industries that companies belong to based on their business activities. If sic_codes is not passed in, we will perform an internal lookup with naics_code.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<String>> sicCodes() {
        return (Optional<List<String>>) sicCodes;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * Industry title
     */
    public PutV1CompanyIndustryRequestBody withTitle(String title) {
        Utils.checkNotNull(title, "title");
        this.title = Optional.ofNullable(title);
        return this;
    }

    /**
     * Industry title
     */
    public PutV1CompanyIndustryRequestBody withTitle(Optional<String> title) {
        Utils.checkNotNull(title, "title");
        this.title = title;
        return this;
    }

    /**
     * North American Industry Classification System (NAICS) is used to classify businesses with a six digit number based on the primary type of work the business performs
     */
    public PutV1CompanyIndustryRequestBody withNaicsCode(String naicsCode) {
        Utils.checkNotNull(naicsCode, "naicsCode");
        this.naicsCode = naicsCode;
        return this;
    }

    /**
     * A list of Standard Industrial Classification (SIC) codes, which are four digit number that categorize the industries that companies belong to based on their business activities. If sic_codes is not passed in, we will perform an internal lookup with naics_code.
     */
    public PutV1CompanyIndustryRequestBody withSicCodes(List<String> sicCodes) {
        Utils.checkNotNull(sicCodes, "sicCodes");
        this.sicCodes = Optional.ofNullable(sicCodes);
        return this;
    }

    /**
     * A list of Standard Industrial Classification (SIC) codes, which are four digit number that categorize the industries that companies belong to based on their business activities. If sic_codes is not passed in, we will perform an internal lookup with naics_code.
     */
    public PutV1CompanyIndustryRequestBody withSicCodes(Optional<? extends List<String>> sicCodes) {
        Utils.checkNotNull(sicCodes, "sicCodes");
        this.sicCodes = sicCodes;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PutV1CompanyIndustryRequestBody other = (PutV1CompanyIndustryRequestBody) o;
        return 
            Objects.deepEquals(this.title, other.title) &&
            Objects.deepEquals(this.naicsCode, other.naicsCode) &&
            Objects.deepEquals(this.sicCodes, other.sicCodes);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            title,
            naicsCode,
            sicCodes);
    }
    
    @Override
    public String toString() {
        return Utils.toString(PutV1CompanyIndustryRequestBody.class,
                "title", title,
                "naicsCode", naicsCode,
                "sicCodes", sicCodes);
    }
    
    public final static class Builder {
 
        private Optional<String> title = Optional.empty();
 
        private String naicsCode;
 
        private Optional<? extends List<String>> sicCodes = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * Industry title
         */
        public Builder title(String title) {
            Utils.checkNotNull(title, "title");
            this.title = Optional.ofNullable(title);
            return this;
        }

        /**
         * Industry title
         */
        public Builder title(Optional<String> title) {
            Utils.checkNotNull(title, "title");
            this.title = title;
            return this;
        }

        /**
         * North American Industry Classification System (NAICS) is used to classify businesses with a six digit number based on the primary type of work the business performs
         */
        public Builder naicsCode(String naicsCode) {
            Utils.checkNotNull(naicsCode, "naicsCode");
            this.naicsCode = naicsCode;
            return this;
        }

        /**
         * A list of Standard Industrial Classification (SIC) codes, which are four digit number that categorize the industries that companies belong to based on their business activities. If sic_codes is not passed in, we will perform an internal lookup with naics_code.
         */
        public Builder sicCodes(List<String> sicCodes) {
            Utils.checkNotNull(sicCodes, "sicCodes");
            this.sicCodes = Optional.ofNullable(sicCodes);
            return this;
        }

        /**
         * A list of Standard Industrial Classification (SIC) codes, which are four digit number that categorize the industries that companies belong to based on their business activities. If sic_codes is not passed in, we will perform an internal lookup with naics_code.
         */
        public Builder sicCodes(Optional<? extends List<String>> sicCodes) {
            Utils.checkNotNull(sicCodes, "sicCodes");
            this.sicCodes = sicCodes;
            return this;
        }
        
        public PutV1CompanyIndustryRequestBody build() {
            return new PutV1CompanyIndustryRequestBody(
                title,
                naicsCode,
                sicCodes);
        }
    }
}

