/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gusto.embedded_api.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.core.type.TypeReference;
import com.gusto.embedded_api.models.components.WireInRequestUpdateRequestBody;
import com.gusto.embedded_api.utils.LazySingletonValue;
import com.gusto.embedded_api.utils.SpeakeasyMetadata;
import com.gusto.embedded_api.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Optional;


public class PutWireInRequestsWireInRequestUuidRequest {
    /**
     * Determines the date-based API version associated with your API call. If none is provided, your
     * application's [minimum API
     * version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=X-Gusto-API-Version")
    private Optional<? extends PutWireInRequestsWireInRequestUuidHeaderXGustoAPIVersion> xGustoAPIVersion;

    /**
     * The UUID of the Wire In Request
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=wire_in_request_uuid")
    private String wireInRequestUuid;


    @SpeakeasyMetadata("request:mediaType=application/json")
    private WireInRequestUpdateRequestBody wireInRequestUpdateRequestBody;

    @JsonCreator
    public PutWireInRequestsWireInRequestUuidRequest(
            Optional<? extends PutWireInRequestsWireInRequestUuidHeaderXGustoAPIVersion> xGustoAPIVersion,
            String wireInRequestUuid,
            WireInRequestUpdateRequestBody wireInRequestUpdateRequestBody) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        Utils.checkNotNull(wireInRequestUuid, "wireInRequestUuid");
        Utils.checkNotNull(wireInRequestUpdateRequestBody, "wireInRequestUpdateRequestBody");
        this.xGustoAPIVersion = xGustoAPIVersion;
        this.wireInRequestUuid = wireInRequestUuid;
        this.wireInRequestUpdateRequestBody = wireInRequestUpdateRequestBody;
    }
    
    public PutWireInRequestsWireInRequestUuidRequest(
            String wireInRequestUuid,
            WireInRequestUpdateRequestBody wireInRequestUpdateRequestBody) {
        this(Optional.empty(), wireInRequestUuid, wireInRequestUpdateRequestBody);
    }

    /**
     * Determines the date-based API version associated with your API call. If none is provided, your
     * application's [minimum API
     * version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<PutWireInRequestsWireInRequestUuidHeaderXGustoAPIVersion> xGustoAPIVersion() {
        return (Optional<PutWireInRequestsWireInRequestUuidHeaderXGustoAPIVersion>) xGustoAPIVersion;
    }

    /**
     * The UUID of the Wire In Request
     */
    @JsonIgnore
    public String wireInRequestUuid() {
        return wireInRequestUuid;
    }

    @JsonIgnore
    public WireInRequestUpdateRequestBody wireInRequestUpdateRequestBody() {
        return wireInRequestUpdateRequestBody;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Determines the date-based API version associated with your API call. If none is provided, your
     * application's [minimum API
     * version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
     */
    public PutWireInRequestsWireInRequestUuidRequest withXGustoAPIVersion(PutWireInRequestsWireInRequestUuidHeaderXGustoAPIVersion xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = Optional.ofNullable(xGustoAPIVersion);
        return this;
    }


    /**
     * Determines the date-based API version associated with your API call. If none is provided, your
     * application's [minimum API
     * version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
     */
    public PutWireInRequestsWireInRequestUuidRequest withXGustoAPIVersion(Optional<? extends PutWireInRequestsWireInRequestUuidHeaderXGustoAPIVersion> xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = xGustoAPIVersion;
        return this;
    }

    /**
     * The UUID of the Wire In Request
     */
    public PutWireInRequestsWireInRequestUuidRequest withWireInRequestUuid(String wireInRequestUuid) {
        Utils.checkNotNull(wireInRequestUuid, "wireInRequestUuid");
        this.wireInRequestUuid = wireInRequestUuid;
        return this;
    }

    public PutWireInRequestsWireInRequestUuidRequest withWireInRequestUpdateRequestBody(WireInRequestUpdateRequestBody wireInRequestUpdateRequestBody) {
        Utils.checkNotNull(wireInRequestUpdateRequestBody, "wireInRequestUpdateRequestBody");
        this.wireInRequestUpdateRequestBody = wireInRequestUpdateRequestBody;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PutWireInRequestsWireInRequestUuidRequest other = (PutWireInRequestsWireInRequestUuidRequest) o;
        return 
            Utils.enhancedDeepEquals(this.xGustoAPIVersion, other.xGustoAPIVersion) &&
            Utils.enhancedDeepEquals(this.wireInRequestUuid, other.wireInRequestUuid) &&
            Utils.enhancedDeepEquals(this.wireInRequestUpdateRequestBody, other.wireInRequestUpdateRequestBody);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            xGustoAPIVersion, wireInRequestUuid, wireInRequestUpdateRequestBody);
    }
    
    @Override
    public String toString() {
        return Utils.toString(PutWireInRequestsWireInRequestUuidRequest.class,
                "xGustoAPIVersion", xGustoAPIVersion,
                "wireInRequestUuid", wireInRequestUuid,
                "wireInRequestUpdateRequestBody", wireInRequestUpdateRequestBody);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<? extends PutWireInRequestsWireInRequestUuidHeaderXGustoAPIVersion> xGustoAPIVersion;

        private String wireInRequestUuid;

        private WireInRequestUpdateRequestBody wireInRequestUpdateRequestBody;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * Determines the date-based API version associated with your API call. If none is provided, your
         * application's [minimum API
         * version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
         */
        public Builder xGustoAPIVersion(PutWireInRequestsWireInRequestUuidHeaderXGustoAPIVersion xGustoAPIVersion) {
            Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
            this.xGustoAPIVersion = Optional.ofNullable(xGustoAPIVersion);
            return this;
        }

        /**
         * Determines the date-based API version associated with your API call. If none is provided, your
         * application's [minimum API
         * version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
         */
        public Builder xGustoAPIVersion(Optional<? extends PutWireInRequestsWireInRequestUuidHeaderXGustoAPIVersion> xGustoAPIVersion) {
            Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
            this.xGustoAPIVersion = xGustoAPIVersion;
            return this;
        }


        /**
         * The UUID of the Wire In Request
         */
        public Builder wireInRequestUuid(String wireInRequestUuid) {
            Utils.checkNotNull(wireInRequestUuid, "wireInRequestUuid");
            this.wireInRequestUuid = wireInRequestUuid;
            return this;
        }


        public Builder wireInRequestUpdateRequestBody(WireInRequestUpdateRequestBody wireInRequestUpdateRequestBody) {
            Utils.checkNotNull(wireInRequestUpdateRequestBody, "wireInRequestUpdateRequestBody");
            this.wireInRequestUpdateRequestBody = wireInRequestUpdateRequestBody;
            return this;
        }

        public PutWireInRequestsWireInRequestUuidRequest build() {
            if (xGustoAPIVersion == null) {
                xGustoAPIVersion = _SINGLETON_VALUE_XGustoAPIVersion.value();
            }

            return new PutWireInRequestsWireInRequestUuidRequest(
                xGustoAPIVersion, wireInRequestUuid, wireInRequestUpdateRequestBody);
        }


        private static final LazySingletonValue<Optional<? extends PutWireInRequestsWireInRequestUuidHeaderXGustoAPIVersion>> _SINGLETON_VALUE_XGustoAPIVersion =
                new LazySingletonValue<>(
                        "X-Gusto-API-Version",
                        "\"2025-06-15\"",
                        new TypeReference<Optional<? extends PutWireInRequestsWireInRequestUuidHeaderXGustoAPIVersion>>() {});
    }
}
