/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gusto.embedded_api.models.operations.async;

import static com.gusto.embedded_api.operations.Operations.AsyncRequestOperation;

import com.fasterxml.jackson.core.type.TypeReference;
import com.gusto.embedded_api.SDKConfiguration;
import com.gusto.embedded_api.models.components.PayScheduleAssignmentBody;
import com.gusto.embedded_api.models.components.VersionHeader;
import com.gusto.embedded_api.models.operations.PostV1CompaniesCompanyIdPaySchedulesAssignRequest;
import com.gusto.embedded_api.operations.PostV1CompaniesCompanyIdPaySchedulesAssign;
import com.gusto.embedded_api.utils.Headers;
import com.gusto.embedded_api.utils.LazySingletonValue;
import com.gusto.embedded_api.utils.Utils;
import java.lang.Exception;
import java.lang.String;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;

public class PostV1CompaniesCompanyIdPaySchedulesAssignRequestBuilder {

    private String companyId;
    private Optional<? extends VersionHeader> xGustoAPIVersion = Utils.readDefaultOrConstValue(
                            "xGustoAPIVersion",
                            "\"2024-04-01\"",
                            new TypeReference<Optional<? extends VersionHeader>>() {});
    private PayScheduleAssignmentBody payScheduleAssignmentBody;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public PostV1CompaniesCompanyIdPaySchedulesAssignRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public PostV1CompaniesCompanyIdPaySchedulesAssignRequestBuilder companyId(String companyId) {
        Utils.checkNotNull(companyId, "companyId");
        this.companyId = companyId;
        return this;
    }
                
    public PostV1CompaniesCompanyIdPaySchedulesAssignRequestBuilder xGustoAPIVersion(VersionHeader xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = Optional.of(xGustoAPIVersion);
        return this;
    }

    public PostV1CompaniesCompanyIdPaySchedulesAssignRequestBuilder xGustoAPIVersion(Optional<? extends VersionHeader> xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = xGustoAPIVersion;
        return this;
    }

    public PostV1CompaniesCompanyIdPaySchedulesAssignRequestBuilder payScheduleAssignmentBody(PayScheduleAssignmentBody payScheduleAssignmentBody) {
        Utils.checkNotNull(payScheduleAssignmentBody, "payScheduleAssignmentBody");
        this.payScheduleAssignmentBody = payScheduleAssignmentBody;
        return this;
    }


    private PostV1CompaniesCompanyIdPaySchedulesAssignRequest buildRequest() {
        if (xGustoAPIVersion == null) {
            xGustoAPIVersion = _SINGLETON_VALUE_XGustoAPIVersion.value();
        }

        PostV1CompaniesCompanyIdPaySchedulesAssignRequest request = new PostV1CompaniesCompanyIdPaySchedulesAssignRequest(companyId,
            xGustoAPIVersion,
            payScheduleAssignmentBody);

        return request;
    }

    public CompletableFuture<PostV1CompaniesCompanyIdPaySchedulesAssignResponse> call() throws Exception {
        
        AsyncRequestOperation<PostV1CompaniesCompanyIdPaySchedulesAssignRequest, PostV1CompaniesCompanyIdPaySchedulesAssignResponse> operation
              = new PostV1CompaniesCompanyIdPaySchedulesAssign.Async(sdkConfiguration, _headers);
        PostV1CompaniesCompanyIdPaySchedulesAssignRequest request = buildRequest();

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

    private static final LazySingletonValue<Optional<? extends VersionHeader>> _SINGLETON_VALUE_XGustoAPIVersion =
            new LazySingletonValue<>(
                    "xGustoAPIVersion",
                    "\"2024-04-01\"",
                    new TypeReference<Optional<? extends VersionHeader>>() {});
}
