/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations.async;

import static org.openapis.openapi.operations.Operations.AsyncRequestOperation;

import java.util.concurrent.CompletableFuture;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.models.operations.GetV1CompaniesCompanyUuidTimeOffRequestsRequest;
import org.openapis.openapi.operations.GetV1CompaniesCompanyUuidTimeOffRequests;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Utils;

public class GetV1CompaniesCompanyUuidTimeOffRequestsRequestBuilder {

    private GetV1CompaniesCompanyUuidTimeOffRequestsRequest request;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public GetV1CompaniesCompanyUuidTimeOffRequestsRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public GetV1CompaniesCompanyUuidTimeOffRequestsRequestBuilder request(GetV1CompaniesCompanyUuidTimeOffRequestsRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public CompletableFuture<GetV1CompaniesCompanyUuidTimeOffRequestsResponse> call() {
        
        AsyncRequestOperation<GetV1CompaniesCompanyUuidTimeOffRequestsRequest, GetV1CompaniesCompanyUuidTimeOffRequestsResponse> operation
              = new GetV1CompaniesCompanyUuidTimeOffRequests.Async(sdkConfiguration, _headers);

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }
}
