/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations.async;

import static org.openapis.openapi.operations.Operations.AsyncRequestOperation;

import com.fasterxml.jackson.core.type.TypeReference;
import java.lang.String;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.models.components.PayrollGrossUpRequest;
import org.openapis.openapi.models.operations.PostPayrollsGrossUpPayrollUuidHeaderXGustoAPIVersion;
import org.openapis.openapi.models.operations.PostPayrollsGrossUpPayrollUuidRequest;
import org.openapis.openapi.operations.PostPayrollsGrossUpPayrollUuid;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.LazySingletonValue;
import org.openapis.openapi.utils.Utils;

public class PostPayrollsGrossUpPayrollUuidRequestBuilder {

    private Optional<? extends PostPayrollsGrossUpPayrollUuidHeaderXGustoAPIVersion> xGustoAPIVersion = Utils.readDefaultOrConstValue(
                            "xGustoAPIVersion",
                            "\"2025-11-15\"",
                            new TypeReference<Optional<? extends PostPayrollsGrossUpPayrollUuidHeaderXGustoAPIVersion>>() {});
    private String payrollUuid;
    private PayrollGrossUpRequest payrollGrossUpRequest;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public PostPayrollsGrossUpPayrollUuidRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }
                
    public PostPayrollsGrossUpPayrollUuidRequestBuilder xGustoAPIVersion(PostPayrollsGrossUpPayrollUuidHeaderXGustoAPIVersion xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = Optional.of(xGustoAPIVersion);
        return this;
    }

    public PostPayrollsGrossUpPayrollUuidRequestBuilder xGustoAPIVersion(Optional<? extends PostPayrollsGrossUpPayrollUuidHeaderXGustoAPIVersion> xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = xGustoAPIVersion;
        return this;
    }

    public PostPayrollsGrossUpPayrollUuidRequestBuilder payrollUuid(String payrollUuid) {
        Utils.checkNotNull(payrollUuid, "payrollUuid");
        this.payrollUuid = payrollUuid;
        return this;
    }

    public PostPayrollsGrossUpPayrollUuidRequestBuilder payrollGrossUpRequest(PayrollGrossUpRequest payrollGrossUpRequest) {
        Utils.checkNotNull(payrollGrossUpRequest, "payrollGrossUpRequest");
        this.payrollGrossUpRequest = payrollGrossUpRequest;
        return this;
    }


    private PostPayrollsGrossUpPayrollUuidRequest buildRequest() {
        if (xGustoAPIVersion == null) {
            xGustoAPIVersion = _SINGLETON_VALUE_XGustoAPIVersion.value();
        }

        PostPayrollsGrossUpPayrollUuidRequest request = new PostPayrollsGrossUpPayrollUuidRequest(xGustoAPIVersion,
            payrollUuid,
            payrollGrossUpRequest);

        return request;
    }

    public CompletableFuture<PostPayrollsGrossUpPayrollUuidResponse> call() {
        
        AsyncRequestOperation<PostPayrollsGrossUpPayrollUuidRequest, PostPayrollsGrossUpPayrollUuidResponse> operation
              = new PostPayrollsGrossUpPayrollUuid.Async(sdkConfiguration, _headers);
        PostPayrollsGrossUpPayrollUuidRequest request = buildRequest();

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

    private static final LazySingletonValue<Optional<? extends PostPayrollsGrossUpPayrollUuidHeaderXGustoAPIVersion>> _SINGLETON_VALUE_XGustoAPIVersion =
            new LazySingletonValue<>(
                    "xGustoAPIVersion",
                    "\"2025-11-15\"",
                    new TypeReference<Optional<? extends PostPayrollsGrossUpPayrollUuidHeaderXGustoAPIVersion>>() {});
}
