/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations.async;

import static org.openapis.openapi.operations.Operations.AsyncRequestOperation;

import com.fasterxml.jackson.core.type.TypeReference;
import java.lang.String;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.models.operations.PutV1HomeAddressesHomeAddressUuidHeaderXGustoAPIVersion;
import org.openapis.openapi.models.operations.PutV1HomeAddressesHomeAddressUuidRequest;
import org.openapis.openapi.models.operations.PutV1HomeAddressesHomeAddressUuidRequestBody;
import org.openapis.openapi.operations.PutV1HomeAddressesHomeAddressUuid;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.LazySingletonValue;
import org.openapis.openapi.utils.Utils;

public class PutV1HomeAddressesHomeAddressUuidRequestBuilder {

    private Optional<? extends PutV1HomeAddressesHomeAddressUuidHeaderXGustoAPIVersion> xGustoAPIVersion = Utils.readDefaultOrConstValue(
                            "xGustoAPIVersion",
                            "\"2025-11-15\"",
                            new TypeReference<Optional<? extends PutV1HomeAddressesHomeAddressUuidHeaderXGustoAPIVersion>>() {});
    private String homeAddressUuid;
    private PutV1HomeAddressesHomeAddressUuidRequestBody requestBody;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public PutV1HomeAddressesHomeAddressUuidRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }
                
    public PutV1HomeAddressesHomeAddressUuidRequestBuilder xGustoAPIVersion(PutV1HomeAddressesHomeAddressUuidHeaderXGustoAPIVersion xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = Optional.of(xGustoAPIVersion);
        return this;
    }

    public PutV1HomeAddressesHomeAddressUuidRequestBuilder xGustoAPIVersion(Optional<? extends PutV1HomeAddressesHomeAddressUuidHeaderXGustoAPIVersion> xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = xGustoAPIVersion;
        return this;
    }

    public PutV1HomeAddressesHomeAddressUuidRequestBuilder homeAddressUuid(String homeAddressUuid) {
        Utils.checkNotNull(homeAddressUuid, "homeAddressUuid");
        this.homeAddressUuid = homeAddressUuid;
        return this;
    }

    public PutV1HomeAddressesHomeAddressUuidRequestBuilder requestBody(PutV1HomeAddressesHomeAddressUuidRequestBody requestBody) {
        Utils.checkNotNull(requestBody, "requestBody");
        this.requestBody = requestBody;
        return this;
    }


    private PutV1HomeAddressesHomeAddressUuidRequest buildRequest() {
        if (xGustoAPIVersion == null) {
            xGustoAPIVersion = _SINGLETON_VALUE_XGustoAPIVersion.value();
        }

        PutV1HomeAddressesHomeAddressUuidRequest request = new PutV1HomeAddressesHomeAddressUuidRequest(xGustoAPIVersion,
            homeAddressUuid,
            requestBody);

        return request;
    }

    public CompletableFuture<PutV1HomeAddressesHomeAddressUuidResponse> call() {
        
        AsyncRequestOperation<PutV1HomeAddressesHomeAddressUuidRequest, PutV1HomeAddressesHomeAddressUuidResponse> operation
              = new PutV1HomeAddressesHomeAddressUuid.Async(sdkConfiguration, _headers);
        PutV1HomeAddressesHomeAddressUuidRequest request = buildRequest();

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

    private static final LazySingletonValue<Optional<? extends PutV1HomeAddressesHomeAddressUuidHeaderXGustoAPIVersion>> _SINGLETON_VALUE_XGustoAPIVersion =
            new LazySingletonValue<>(
                    "xGustoAPIVersion",
                    "\"2025-11-15\"",
                    new TypeReference<Optional<? extends PutV1HomeAddressesHomeAddressUuidHeaderXGustoAPIVersion>>() {});
}
