/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gusto.embedded_api_v_2025_11_15.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.core.type.TypeReference;
import com.gusto.embedded_api_v_2025_11_15.utils.LazySingletonValue;
import com.gusto.embedded_api_v_2025_11_15.utils.SpeakeasyMetadata;
import com.gusto.embedded_api_v_2025_11_15.utils.Utils;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Optional;


public class GetReverseWireTransactionsRequest {
    /**
     * Determines the date-based API version associated with your API call. If none is provided, your
     * application's [minimum API
     * version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=X-Gusto-API-Version")
    private Optional<? extends GetReverseWireTransactionsHeaderXGustoAPIVersion> xGustoAPIVersion;

    /**
     * The UUID of the company
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=company_uuid")
    private String companyUuid;

    /**
     * Filter results to reverse wires associated with a specific payroll
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=payroll_uuid")
    private Optional<String> payrollUuid;

    /**
     * The page that is requested. When unspecified, will load all objects unless endpoint forces
     * pagination.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=page")
    private Optional<Long> page;

    /**
     * Number of objects per page. For majority of endpoints will default to 25
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=per")
    private Optional<Long> per;

    @JsonCreator
    public GetReverseWireTransactionsRequest(
            Optional<? extends GetReverseWireTransactionsHeaderXGustoAPIVersion> xGustoAPIVersion,
            String companyUuid,
            Optional<String> payrollUuid,
            Optional<Long> page,
            Optional<Long> per) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        Utils.checkNotNull(companyUuid, "companyUuid");
        Utils.checkNotNull(payrollUuid, "payrollUuid");
        Utils.checkNotNull(page, "page");
        Utils.checkNotNull(per, "per");
        this.xGustoAPIVersion = xGustoAPIVersion;
        this.companyUuid = companyUuid;
        this.payrollUuid = payrollUuid;
        this.page = page;
        this.per = per;
    }
    
    public GetReverseWireTransactionsRequest(
            String companyUuid) {
        this(Optional.empty(), companyUuid, Optional.empty(),
            Optional.empty(), Optional.empty());
    }

    /**
     * Determines the date-based API version associated with your API call. If none is provided, your
     * application's [minimum API
     * version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<GetReverseWireTransactionsHeaderXGustoAPIVersion> xGustoAPIVersion() {
        return (Optional<GetReverseWireTransactionsHeaderXGustoAPIVersion>) xGustoAPIVersion;
    }

    /**
     * The UUID of the company
     */
    @JsonIgnore
    public String companyUuid() {
        return companyUuid;
    }

    /**
     * Filter results to reverse wires associated with a specific payroll
     */
    @JsonIgnore
    public Optional<String> payrollUuid() {
        return payrollUuid;
    }

    /**
     * The page that is requested. When unspecified, will load all objects unless endpoint forces
     * pagination.
     */
    @JsonIgnore
    public Optional<Long> page() {
        return page;
    }

    /**
     * Number of objects per page. For majority of endpoints will default to 25
     */
    @JsonIgnore
    public Optional<Long> per() {
        return per;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Determines the date-based API version associated with your API call. If none is provided, your
     * application's [minimum API
     * version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
     */
    public GetReverseWireTransactionsRequest withXGustoAPIVersion(GetReverseWireTransactionsHeaderXGustoAPIVersion xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = Optional.ofNullable(xGustoAPIVersion);
        return this;
    }


    /**
     * Determines the date-based API version associated with your API call. If none is provided, your
     * application's [minimum API
     * version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
     */
    public GetReverseWireTransactionsRequest withXGustoAPIVersion(Optional<? extends GetReverseWireTransactionsHeaderXGustoAPIVersion> xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = xGustoAPIVersion;
        return this;
    }

    /**
     * The UUID of the company
     */
    public GetReverseWireTransactionsRequest withCompanyUuid(String companyUuid) {
        Utils.checkNotNull(companyUuid, "companyUuid");
        this.companyUuid = companyUuid;
        return this;
    }

    /**
     * Filter results to reverse wires associated with a specific payroll
     */
    public GetReverseWireTransactionsRequest withPayrollUuid(String payrollUuid) {
        Utils.checkNotNull(payrollUuid, "payrollUuid");
        this.payrollUuid = Optional.ofNullable(payrollUuid);
        return this;
    }


    /**
     * Filter results to reverse wires associated with a specific payroll
     */
    public GetReverseWireTransactionsRequest withPayrollUuid(Optional<String> payrollUuid) {
        Utils.checkNotNull(payrollUuid, "payrollUuid");
        this.payrollUuid = payrollUuid;
        return this;
    }

    /**
     * The page that is requested. When unspecified, will load all objects unless endpoint forces
     * pagination.
     */
    public GetReverseWireTransactionsRequest withPage(long page) {
        Utils.checkNotNull(page, "page");
        this.page = Optional.ofNullable(page);
        return this;
    }


    /**
     * The page that is requested. When unspecified, will load all objects unless endpoint forces
     * pagination.
     */
    public GetReverseWireTransactionsRequest withPage(Optional<Long> page) {
        Utils.checkNotNull(page, "page");
        this.page = page;
        return this;
    }

    /**
     * Number of objects per page. For majority of endpoints will default to 25
     */
    public GetReverseWireTransactionsRequest withPer(long per) {
        Utils.checkNotNull(per, "per");
        this.per = Optional.ofNullable(per);
        return this;
    }


    /**
     * Number of objects per page. For majority of endpoints will default to 25
     */
    public GetReverseWireTransactionsRequest withPer(Optional<Long> per) {
        Utils.checkNotNull(per, "per");
        this.per = per;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetReverseWireTransactionsRequest other = (GetReverseWireTransactionsRequest) o;
        return 
            Utils.enhancedDeepEquals(this.xGustoAPIVersion, other.xGustoAPIVersion) &&
            Utils.enhancedDeepEquals(this.companyUuid, other.companyUuid) &&
            Utils.enhancedDeepEquals(this.payrollUuid, other.payrollUuid) &&
            Utils.enhancedDeepEquals(this.page, other.page) &&
            Utils.enhancedDeepEquals(this.per, other.per);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            xGustoAPIVersion, companyUuid, payrollUuid,
            page, per);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetReverseWireTransactionsRequest.class,
                "xGustoAPIVersion", xGustoAPIVersion,
                "companyUuid", companyUuid,
                "payrollUuid", payrollUuid,
                "page", page,
                "per", per);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<? extends GetReverseWireTransactionsHeaderXGustoAPIVersion> xGustoAPIVersion;

        private String companyUuid;

        private Optional<String> payrollUuid = Optional.empty();

        private Optional<Long> page = Optional.empty();

        private Optional<Long> per = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * Determines the date-based API version associated with your API call. If none is provided, your
         * application's [minimum API
         * version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
         */
        public Builder xGustoAPIVersion(GetReverseWireTransactionsHeaderXGustoAPIVersion xGustoAPIVersion) {
            Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
            this.xGustoAPIVersion = Optional.ofNullable(xGustoAPIVersion);
            return this;
        }

        /**
         * Determines the date-based API version associated with your API call. If none is provided, your
         * application's [minimum API
         * version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
         */
        public Builder xGustoAPIVersion(Optional<? extends GetReverseWireTransactionsHeaderXGustoAPIVersion> xGustoAPIVersion) {
            Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
            this.xGustoAPIVersion = xGustoAPIVersion;
            return this;
        }


        /**
         * The UUID of the company
         */
        public Builder companyUuid(String companyUuid) {
            Utils.checkNotNull(companyUuid, "companyUuid");
            this.companyUuid = companyUuid;
            return this;
        }


        /**
         * Filter results to reverse wires associated with a specific payroll
         */
        public Builder payrollUuid(String payrollUuid) {
            Utils.checkNotNull(payrollUuid, "payrollUuid");
            this.payrollUuid = Optional.ofNullable(payrollUuid);
            return this;
        }

        /**
         * Filter results to reverse wires associated with a specific payroll
         */
        public Builder payrollUuid(Optional<String> payrollUuid) {
            Utils.checkNotNull(payrollUuid, "payrollUuid");
            this.payrollUuid = payrollUuid;
            return this;
        }


        /**
         * The page that is requested. When unspecified, will load all objects unless endpoint forces
         * pagination.
         */
        public Builder page(long page) {
            Utils.checkNotNull(page, "page");
            this.page = Optional.ofNullable(page);
            return this;
        }

        /**
         * The page that is requested. When unspecified, will load all objects unless endpoint forces
         * pagination.
         */
        public Builder page(Optional<Long> page) {
            Utils.checkNotNull(page, "page");
            this.page = page;
            return this;
        }


        /**
         * Number of objects per page. For majority of endpoints will default to 25
         */
        public Builder per(long per) {
            Utils.checkNotNull(per, "per");
            this.per = Optional.ofNullable(per);
            return this;
        }

        /**
         * Number of objects per page. For majority of endpoints will default to 25
         */
        public Builder per(Optional<Long> per) {
            Utils.checkNotNull(per, "per");
            this.per = per;
            return this;
        }

        public GetReverseWireTransactionsRequest build() {
            if (xGustoAPIVersion == null) {
                xGustoAPIVersion = _SINGLETON_VALUE_XGustoAPIVersion.value();
            }

            return new GetReverseWireTransactionsRequest(
                xGustoAPIVersion, companyUuid, payrollUuid,
                page, per);
        }


        private static final LazySingletonValue<Optional<? extends GetReverseWireTransactionsHeaderXGustoAPIVersion>> _SINGLETON_VALUE_XGustoAPIVersion =
                new LazySingletonValue<>(
                        "X-Gusto-API-Version",
                        "\"2025-11-15\"",
                        new TypeReference<Optional<? extends GetReverseWireTransactionsHeaderXGustoAPIVersion>>() {});
    }
}
