/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gusto.embedded_api_v_2025_11_15.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.gusto.embedded_api_v_2025_11_15.models.components.PayrollBatchResults;
import com.gusto.embedded_api_v_2025_11_15.utils.Response;
import com.gusto.embedded_api_v_2025_11_15.utils.Utils;
import java.io.InputStream;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Optional;


public class GetV1PayrollBatchesPayrollBatchUuidResponse implements Response {
    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    /**
     * successful
     */
    private Optional<? extends PayrollBatchResults> payrollBatchResults;

    @JsonCreator
    public GetV1PayrollBatchesPayrollBatchUuidResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse,
            Optional<? extends PayrollBatchResults> payrollBatchResults) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(payrollBatchResults, "payrollBatchResults");
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.payrollBatchResults = payrollBatchResults;
    }
    
    public GetV1PayrollBatchesPayrollBatchUuidResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        this(contentType, statusCode, rawResponse,
            Optional.empty());
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }

    /**
     * successful
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<PayrollBatchResults> payrollBatchResults() {
        return (Optional<PayrollBatchResults>) payrollBatchResults;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * HTTP response content type for this operation
     */
    public GetV1PayrollBatchesPayrollBatchUuidResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public GetV1PayrollBatchesPayrollBatchUuidResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public GetV1PayrollBatchesPayrollBatchUuidResponse withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    /**
     * successful
     */
    public GetV1PayrollBatchesPayrollBatchUuidResponse withPayrollBatchResults(PayrollBatchResults payrollBatchResults) {
        Utils.checkNotNull(payrollBatchResults, "payrollBatchResults");
        this.payrollBatchResults = Optional.ofNullable(payrollBatchResults);
        return this;
    }


    /**
     * successful
     */
    public GetV1PayrollBatchesPayrollBatchUuidResponse withPayrollBatchResults(Optional<? extends PayrollBatchResults> payrollBatchResults) {
        Utils.checkNotNull(payrollBatchResults, "payrollBatchResults");
        this.payrollBatchResults = payrollBatchResults;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetV1PayrollBatchesPayrollBatchUuidResponse other = (GetV1PayrollBatchesPayrollBatchUuidResponse) o;
        return 
            Utils.enhancedDeepEquals(this.contentType, other.contentType) &&
            Utils.enhancedDeepEquals(this.statusCode, other.statusCode) &&
            Utils.enhancedDeepEquals(this.rawResponse, other.rawResponse) &&
            Utils.enhancedDeepEquals(this.payrollBatchResults, other.payrollBatchResults);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            contentType, statusCode, rawResponse,
            payrollBatchResults);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetV1PayrollBatchesPayrollBatchUuidResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "payrollBatchResults", payrollBatchResults);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String contentType;

        private Integer statusCode;

        private HttpResponse<InputStream> rawResponse;

        private Optional<? extends PayrollBatchResults> payrollBatchResults = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }


        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }


        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }


        /**
         * successful
         */
        public Builder payrollBatchResults(PayrollBatchResults payrollBatchResults) {
            Utils.checkNotNull(payrollBatchResults, "payrollBatchResults");
            this.payrollBatchResults = Optional.ofNullable(payrollBatchResults);
            return this;
        }

        /**
         * successful
         */
        public Builder payrollBatchResults(Optional<? extends PayrollBatchResults> payrollBatchResults) {
            Utils.checkNotNull(payrollBatchResults, "payrollBatchResults");
            this.payrollBatchResults = payrollBatchResults;
            return this;
        }

        public GetV1PayrollBatchesPayrollBatchUuidResponse build() {

            return new GetV1PayrollBatchesPayrollBatchUuidResponse(
                contentType, statusCode, rawResponse,
                payrollBatchResults);
        }

    }
}
