/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gusto.embedded_api_v_2025_11_15.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * BulkReportItemResultReportType
 * 
 * <p>Which report this entry refers to.
 */
public enum BulkReportItemResultReportType {
    CUSTOM_REPORT("custom_report"),
    GENERAL_LEDGER("general_ledger");

    @JsonValue
    private final String value;

    BulkReportItemResultReportType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<BulkReportItemResultReportType> fromValue(String value) {
        for (BulkReportItemResultReportType o: BulkReportItemResultReportType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

