/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gusto.embedded_api_v_2025_11_15.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * PayrollShowEmployeeCompensationsOverrideType
 * 
 * <p>Override mode. Only `one_time` is currently exposed.
 */
public enum PayrollShowEmployeeCompensationsOverrideType {
    ONE_TIME("one_time");

    @JsonValue
    private final String value;

    PayrollShowEmployeeCompensationsOverrideType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<PayrollShowEmployeeCompensationsOverrideType> fromValue(String value) {
        for (PayrollShowEmployeeCompensationsOverrideType o: PayrollShowEmployeeCompensationsOverrideType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

