/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.models.components.VersionHeader;
import org.openapis.openapi.utils.Utils;

public class DeleteV1CompaniesCompanyIdContractorPaymentContractorPaymentRequestBuilder {

    private String companyId;
    private String contractorPaymentId;
    private Optional<? extends VersionHeader> xGustoAPIVersion = Optional.empty();
    private final SDKMethodInterfaces.MethodCallDeleteV1CompaniesCompanyIdContractorPaymentContractorPayment sdk;

    public DeleteV1CompaniesCompanyIdContractorPaymentContractorPaymentRequestBuilder(SDKMethodInterfaces.MethodCallDeleteV1CompaniesCompanyIdContractorPaymentContractorPayment sdk) {
        this.sdk = sdk;
    }

    public DeleteV1CompaniesCompanyIdContractorPaymentContractorPaymentRequestBuilder companyId(String companyId) {
        Utils.checkNotNull(companyId, "companyId");
        this.companyId = companyId;
        return this;
    }

    public DeleteV1CompaniesCompanyIdContractorPaymentContractorPaymentRequestBuilder contractorPaymentId(String contractorPaymentId) {
        Utils.checkNotNull(contractorPaymentId, "contractorPaymentId");
        this.contractorPaymentId = contractorPaymentId;
        return this;
    }
                
    public DeleteV1CompaniesCompanyIdContractorPaymentContractorPaymentRequestBuilder xGustoAPIVersion(VersionHeader xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = Optional.of(xGustoAPIVersion);
        return this;
    }

    public DeleteV1CompaniesCompanyIdContractorPaymentContractorPaymentRequestBuilder xGustoAPIVersion(Optional<? extends VersionHeader> xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = xGustoAPIVersion;
        return this;
    }

    public DeleteV1CompaniesCompanyIdContractorPaymentContractorPaymentResponse call() throws Exception {

        return sdk.delete(
            companyId,
            contractorPaymentId,
            xGustoAPIVersion);
    }
}
