/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.models.components.VersionHeader;
import org.openapis.openapi.utils.Utils;

public class GetV1ContractorsContractorUuidAddressRequestBuilder {

    private String contractorUuid;
    private Optional<? extends VersionHeader> xGustoAPIVersion = Optional.empty();
    private final SDKMethodInterfaces.MethodCallGetV1ContractorsContractorUuidAddress sdk;

    public GetV1ContractorsContractorUuidAddressRequestBuilder(SDKMethodInterfaces.MethodCallGetV1ContractorsContractorUuidAddress sdk) {
        this.sdk = sdk;
    }

    public GetV1ContractorsContractorUuidAddressRequestBuilder contractorUuid(String contractorUuid) {
        Utils.checkNotNull(contractorUuid, "contractorUuid");
        this.contractorUuid = contractorUuid;
        return this;
    }
                
    public GetV1ContractorsContractorUuidAddressRequestBuilder xGustoAPIVersion(VersionHeader xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = Optional.of(xGustoAPIVersion);
        return this;
    }

    public GetV1ContractorsContractorUuidAddressRequestBuilder xGustoAPIVersion(Optional<? extends VersionHeader> xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = xGustoAPIVersion;
        return this;
    }

    public GetV1ContractorsContractorUuidAddressResponse call() throws Exception {

        return sdk.getAddress(
            contractorUuid,
            xGustoAPIVersion);
    }
}
