/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;


import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Objects;
import org.openapis.openapi.models.components.CompanyBankAccount;
import org.openapis.openapi.utils.OneOfDeserializer;
import org.openapis.openapi.utils.TypedObject;
import org.openapis.openapi.utils.Utils.JsonShape;
import org.openapis.openapi.utils.Utils.TypeReferenceWithShape;
import org.openapis.openapi.utils.Utils;

/**
 * PostV1PlaidProcessorTokenResponseBody - A JSON object containing bank information
 */

@JsonDeserialize(using = PostV1PlaidProcessorTokenResponseBody._Deserializer.class)
public class PostV1PlaidProcessorTokenResponseBody {

    @JsonValue
    private TypedObject value;
    
    private PostV1PlaidProcessorTokenResponseBody(TypedObject value) {
        this.value = value;
    }

    public static PostV1PlaidProcessorTokenResponseBody of(CompanyBankAccount value) {
        Utils.checkNotNull(value, "value");
        return new PostV1PlaidProcessorTokenResponseBody(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<CompanyBankAccount>(){}));
    }
    
    /**
     * Returns an instance of one of these types:
     * <ul>
     * <li>{@code org.openapis.openapi.models.components.CompanyBankAccount}</li>
     * </ul>
     * 
     * <p>Use {@code instanceof} to determine what type is returned. For example:
     * 
     * <pre>
     * if (obj.value() instanceof String) {
     *     String answer = (String) obj.value();
     *     System.out.println("answer=" + answer);
     * }
     * </pre>
     * 
     * @return value of oneOf type
     **/ 
    public java.lang.Object value() {
        return value.value();
    }    
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PostV1PlaidProcessorTokenResponseBody other = (PostV1PlaidProcessorTokenResponseBody) o;
        return Objects.deepEquals(this.value.value(), other.value.value()); 
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(value.value());
    }
    
    @SuppressWarnings("serial")
    public static final class _Deserializer extends OneOfDeserializer<PostV1PlaidProcessorTokenResponseBody> {

        public _Deserializer() {
            super(PostV1PlaidProcessorTokenResponseBody.class, false,
                  TypeReferenceWithShape.of(new TypeReference<CompanyBankAccount>() {}, JsonShape.DEFAULT));
        }
    }
    
    @Override
    public String toString() {
        return Utils.toString(PostV1PlaidProcessorTokenResponseBody.class,
                "value", value);
    }
 
}
