/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.models.components.VersionHeader;
import org.openapis.openapi.utils.Utils;

public class PostV1CompensationsCompensationIdRequestBuilder {

    private String jobId;
    private Optional<? extends VersionHeader> xGustoAPIVersion = Optional.empty();
    private PostV1CompensationsCompensationIdRequestBody requestBody;
    private final SDKMethodInterfaces.MethodCallPostV1CompensationsCompensationId sdk;

    public PostV1CompensationsCompensationIdRequestBuilder(SDKMethodInterfaces.MethodCallPostV1CompensationsCompensationId sdk) {
        this.sdk = sdk;
    }

    public PostV1CompensationsCompensationIdRequestBuilder jobId(String jobId) {
        Utils.checkNotNull(jobId, "jobId");
        this.jobId = jobId;
        return this;
    }
                
    public PostV1CompensationsCompensationIdRequestBuilder xGustoAPIVersion(VersionHeader xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = Optional.of(xGustoAPIVersion);
        return this;
    }

    public PostV1CompensationsCompensationIdRequestBuilder xGustoAPIVersion(Optional<? extends VersionHeader> xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = xGustoAPIVersion;
        return this;
    }

    public PostV1CompensationsCompensationIdRequestBuilder requestBody(PostV1CompensationsCompensationIdRequestBody requestBody) {
        Utils.checkNotNull(requestBody, "requestBody");
        this.requestBody = requestBody;
        return this;
    }

    public PostV1CompensationsCompensationIdResponse call() throws Exception {

        return sdk.createCompensation(
            jobId,
            xGustoAPIVersion,
            requestBody);
    }
}
