/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.models.components.VersionHeader;
import org.openapis.openapi.utils.Utils;

public class PostV1EmployeesEmployeeIdEmployeeBenefitsRequestBuilder {

    private String employeeId;
    private Optional<? extends VersionHeader> xGustoAPIVersion = Optional.empty();
    private PostV1EmployeesEmployeeIdEmployeeBenefitsRequestBody requestBody;
    private final SDKMethodInterfaces.MethodCallPostV1EmployeesEmployeeIdEmployeeBenefits sdk;

    public PostV1EmployeesEmployeeIdEmployeeBenefitsRequestBuilder(SDKMethodInterfaces.MethodCallPostV1EmployeesEmployeeIdEmployeeBenefits sdk) {
        this.sdk = sdk;
    }

    public PostV1EmployeesEmployeeIdEmployeeBenefitsRequestBuilder employeeId(String employeeId) {
        Utils.checkNotNull(employeeId, "employeeId");
        this.employeeId = employeeId;
        return this;
    }
                
    public PostV1EmployeesEmployeeIdEmployeeBenefitsRequestBuilder xGustoAPIVersion(VersionHeader xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = Optional.of(xGustoAPIVersion);
        return this;
    }

    public PostV1EmployeesEmployeeIdEmployeeBenefitsRequestBuilder xGustoAPIVersion(Optional<? extends VersionHeader> xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = xGustoAPIVersion;
        return this;
    }

    public PostV1EmployeesEmployeeIdEmployeeBenefitsRequestBuilder requestBody(PostV1EmployeesEmployeeIdEmployeeBenefitsRequestBody requestBody) {
        Utils.checkNotNull(requestBody, "requestBody");
        this.requestBody = requestBody;
        return this;
    }

    public PostV1EmployeesEmployeeIdEmployeeBenefitsResponse call() throws Exception {

        return sdk.create(
            employeeId,
            xGustoAPIVersion,
            requestBody);
    }
}
