/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.models.components.VersionHeader;
import org.openapis.openapi.utils.Utils;

public class PostV1CompaniesCompanyIdLocationsRequestBuilder {

    private String companyId;
    private Optional<? extends VersionHeader> xGustoAPIVersion = Optional.empty();
    private PostV1CompaniesCompanyIdLocationsRequestBody requestBody;
    private final SDKMethodInterfaces.MethodCallPostV1CompaniesCompanyIdLocations sdk;

    public PostV1CompaniesCompanyIdLocationsRequestBuilder(SDKMethodInterfaces.MethodCallPostV1CompaniesCompanyIdLocations sdk) {
        this.sdk = sdk;
    }

    public PostV1CompaniesCompanyIdLocationsRequestBuilder companyId(String companyId) {
        Utils.checkNotNull(companyId, "companyId");
        this.companyId = companyId;
        return this;
    }
                
    public PostV1CompaniesCompanyIdLocationsRequestBuilder xGustoAPIVersion(VersionHeader xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = Optional.of(xGustoAPIVersion);
        return this;
    }

    public PostV1CompaniesCompanyIdLocationsRequestBuilder xGustoAPIVersion(Optional<? extends VersionHeader> xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = xGustoAPIVersion;
        return this;
    }

    public PostV1CompaniesCompanyIdLocationsRequestBuilder requestBody(PostV1CompaniesCompanyIdLocationsRequestBody requestBody) {
        Utils.checkNotNull(requestBody, "requestBody");
        this.requestBody = requestBody;
        return this;
    }

    public PostV1CompaniesCompanyIdLocationsResponse call() throws Exception {

        return sdk.create(
            companyId,
            xGustoAPIVersion,
            requestBody);
    }
}
