/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.models.components.VersionHeader;
import org.openapis.openapi.utils.Utils;

public class PutV1TaxLiabilitiesFinishRequestBuilder {

    private String companyUuid;
    private Optional<? extends VersionHeader> xGustoAPIVersion = Optional.empty();
    private final SDKMethodInterfaces.MethodCallPutV1TaxLiabilitiesFinish sdk;

    public PutV1TaxLiabilitiesFinishRequestBuilder(SDKMethodInterfaces.MethodCallPutV1TaxLiabilitiesFinish sdk) {
        this.sdk = sdk;
    }

    public PutV1TaxLiabilitiesFinishRequestBuilder companyUuid(String companyUuid) {
        Utils.checkNotNull(companyUuid, "companyUuid");
        this.companyUuid = companyUuid;
        return this;
    }
                
    public PutV1TaxLiabilitiesFinishRequestBuilder xGustoAPIVersion(VersionHeader xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = Optional.of(xGustoAPIVersion);
        return this;
    }

    public PutV1TaxLiabilitiesFinishRequestBuilder xGustoAPIVersion(Optional<? extends VersionHeader> xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = xGustoAPIVersion;
        return this;
    }

    public PutV1TaxLiabilitiesFinishResponse call() throws Exception {

        return sdk.finalizeTaxLiabilities(
            companyUuid,
            xGustoAPIVersion);
    }
}
