/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gusto.embedded_api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gusto.embedded_api.utils.Utils;
import java.lang.Boolean;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.time.LocalDate;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * PayScheduleUpdateRequest
 * 
 * <p>Request body for updating a pay schedule. Sent in the pay_schedule_update root key. Version is
 * required for optimistic concurrency.
 * 
 * <p>Pay schedules may be automatically adjusted if an onboarded company misses their first pay date; see
 * [Create a pay schedule](https://docs.gusto.com/embedded-payroll/docs/create-a-pay-schedule).
 */
public class PayScheduleUpdateRequest {
    /**
     * Current version of the pay schedule from the GET response; required for optimistic concurrency.
     * Mismatch returns 409 Conflict.
     */
    @JsonProperty("version")
    private String version;

    /**
     * When true, Autopayroll is enabled and payroll runs automatically one day before payroll deadlines.
     * When false, payroll does not run automatically and must be run manually.
     * For API versions before 2025-11-15 the request field is auto_pilot.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("auto_payroll")
    private Optional<Boolean> autoPayroll;

    /**
     * Pay frequency when creating or updating a schedule. Only weekly, bi-weekly, twice per month, and
     * monthly are supported via the API.
     * 
     * <p>- `Every week`: Weekly pay.
     * - `Every other week`: Biweekly pay.
     * - `Twice per month`: Two pay dates per month; require day_1 and day_2 (use 31 for last day of
     * month).
     * - `Monthly`: One pay date per month; require day_1 (1-31).
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("frequency")
    private Optional<? extends PayScheduleFrequencyCreateUpdate> frequency;

    /**
     * ISO 8601 date (YYYY-MM-DD). Required for anchor and period dates in create, update, and preview
     * requests.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("anchor_pay_date")
    private Optional<LocalDate> anchorPayDate;

    /**
     * ISO 8601 date (YYYY-MM-DD). Required for anchor and period dates in create, update, and preview
     * requests.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("anchor_end_of_pay_period")
    private Optional<LocalDate> anchorEndOfPayPeriod;

    /**
     * First pay day of the month (1–31). Required for Twice per month and Monthly; null for Every week and
     * Every other week.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("day_1")
    private JsonNullable<Long> day1;

    /**
     * Second pay day of the month (1–31); only for Twice per month. Use 31 for last day of month. Null for
     * other frequencies.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("day_2")
    private JsonNullable<Long> day2;

    /**
     * Custom name for the pay schedule; null clears it.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("custom_name")
    private JsonNullable<String> customName;

    @JsonCreator
    public PayScheduleUpdateRequest(
            @JsonProperty("version") String version,
            @JsonProperty("auto_payroll") Optional<Boolean> autoPayroll,
            @JsonProperty("frequency") Optional<? extends PayScheduleFrequencyCreateUpdate> frequency,
            @JsonProperty("anchor_pay_date") Optional<LocalDate> anchorPayDate,
            @JsonProperty("anchor_end_of_pay_period") Optional<LocalDate> anchorEndOfPayPeriod,
            @JsonProperty("day_1") JsonNullable<Long> day1,
            @JsonProperty("day_2") JsonNullable<Long> day2,
            @JsonProperty("custom_name") JsonNullable<String> customName) {
        Utils.checkNotNull(version, "version");
        Utils.checkNotNull(autoPayroll, "autoPayroll");
        Utils.checkNotNull(frequency, "frequency");
        Utils.checkNotNull(anchorPayDate, "anchorPayDate");
        Utils.checkNotNull(anchorEndOfPayPeriod, "anchorEndOfPayPeriod");
        Utils.checkNotNull(day1, "day1");
        Utils.checkNotNull(day2, "day2");
        Utils.checkNotNull(customName, "customName");
        this.version = version;
        this.autoPayroll = autoPayroll;
        this.frequency = frequency;
        this.anchorPayDate = anchorPayDate;
        this.anchorEndOfPayPeriod = anchorEndOfPayPeriod;
        this.day1 = day1;
        this.day2 = day2;
        this.customName = customName;
    }
    
    public PayScheduleUpdateRequest(
            String version) {
        this(version, Optional.empty(), Optional.empty(),
            Optional.empty(), Optional.empty(), JsonNullable.undefined(),
            JsonNullable.undefined(), JsonNullable.undefined());
    }

    /**
     * Current version of the pay schedule from the GET response; required for optimistic concurrency.
     * Mismatch returns 409 Conflict.
     */
    @JsonIgnore
    public String version() {
        return version;
    }

    /**
     * When true, Autopayroll is enabled and payroll runs automatically one day before payroll deadlines.
     * When false, payroll does not run automatically and must be run manually.
     * For API versions before 2025-11-15 the request field is auto_pilot.
     */
    @JsonIgnore
    public Optional<Boolean> autoPayroll() {
        return autoPayroll;
    }

    /**
     * Pay frequency when creating or updating a schedule. Only weekly, bi-weekly, twice per month, and
     * monthly are supported via the API.
     * 
     * <p>- `Every week`: Weekly pay.
     * - `Every other week`: Biweekly pay.
     * - `Twice per month`: Two pay dates per month; require day_1 and day_2 (use 31 for last day of
     * month).
     * - `Monthly`: One pay date per month; require day_1 (1-31).
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<PayScheduleFrequencyCreateUpdate> frequency() {
        return (Optional<PayScheduleFrequencyCreateUpdate>) frequency;
    }

    /**
     * ISO 8601 date (YYYY-MM-DD). Required for anchor and period dates in create, update, and preview
     * requests.
     */
    @JsonIgnore
    public Optional<LocalDate> anchorPayDate() {
        return anchorPayDate;
    }

    /**
     * ISO 8601 date (YYYY-MM-DD). Required for anchor and period dates in create, update, and preview
     * requests.
     */
    @JsonIgnore
    public Optional<LocalDate> anchorEndOfPayPeriod() {
        return anchorEndOfPayPeriod;
    }

    /**
     * First pay day of the month (1–31). Required for Twice per month and Monthly; null for Every week and
     * Every other week.
     */
    @JsonIgnore
    public JsonNullable<Long> day1() {
        return day1;
    }

    /**
     * Second pay day of the month (1–31); only for Twice per month. Use 31 for last day of month. Null for
     * other frequencies.
     */
    @JsonIgnore
    public JsonNullable<Long> day2() {
        return day2;
    }

    /**
     * Custom name for the pay schedule; null clears it.
     */
    @JsonIgnore
    public JsonNullable<String> customName() {
        return customName;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Current version of the pay schedule from the GET response; required for optimistic concurrency.
     * Mismatch returns 409 Conflict.
     */
    public PayScheduleUpdateRequest withVersion(String version) {
        Utils.checkNotNull(version, "version");
        this.version = version;
        return this;
    }

    /**
     * When true, Autopayroll is enabled and payroll runs automatically one day before payroll deadlines.
     * When false, payroll does not run automatically and must be run manually.
     * For API versions before 2025-11-15 the request field is auto_pilot.
     */
    public PayScheduleUpdateRequest withAutoPayroll(boolean autoPayroll) {
        Utils.checkNotNull(autoPayroll, "autoPayroll");
        this.autoPayroll = Optional.ofNullable(autoPayroll);
        return this;
    }


    /**
     * When true, Autopayroll is enabled and payroll runs automatically one day before payroll deadlines.
     * When false, payroll does not run automatically and must be run manually.
     * For API versions before 2025-11-15 the request field is auto_pilot.
     */
    public PayScheduleUpdateRequest withAutoPayroll(Optional<Boolean> autoPayroll) {
        Utils.checkNotNull(autoPayroll, "autoPayroll");
        this.autoPayroll = autoPayroll;
        return this;
    }

    /**
     * Pay frequency when creating or updating a schedule. Only weekly, bi-weekly, twice per month, and
     * monthly are supported via the API.
     * 
     * <p>- `Every week`: Weekly pay.
     * - `Every other week`: Biweekly pay.
     * - `Twice per month`: Two pay dates per month; require day_1 and day_2 (use 31 for last day of
     * month).
     * - `Monthly`: One pay date per month; require day_1 (1-31).
     */
    public PayScheduleUpdateRequest withFrequency(PayScheduleFrequencyCreateUpdate frequency) {
        Utils.checkNotNull(frequency, "frequency");
        this.frequency = Optional.ofNullable(frequency);
        return this;
    }


    /**
     * Pay frequency when creating or updating a schedule. Only weekly, bi-weekly, twice per month, and
     * monthly are supported via the API.
     * 
     * <p>- `Every week`: Weekly pay.
     * - `Every other week`: Biweekly pay.
     * - `Twice per month`: Two pay dates per month; require day_1 and day_2 (use 31 for last day of
     * month).
     * - `Monthly`: One pay date per month; require day_1 (1-31).
     */
    public PayScheduleUpdateRequest withFrequency(Optional<? extends PayScheduleFrequencyCreateUpdate> frequency) {
        Utils.checkNotNull(frequency, "frequency");
        this.frequency = frequency;
        return this;
    }

    /**
     * ISO 8601 date (YYYY-MM-DD). Required for anchor and period dates in create, update, and preview
     * requests.
     */
    public PayScheduleUpdateRequest withAnchorPayDate(LocalDate anchorPayDate) {
        Utils.checkNotNull(anchorPayDate, "anchorPayDate");
        this.anchorPayDate = Optional.ofNullable(anchorPayDate);
        return this;
    }


    /**
     * ISO 8601 date (YYYY-MM-DD). Required for anchor and period dates in create, update, and preview
     * requests.
     */
    public PayScheduleUpdateRequest withAnchorPayDate(Optional<LocalDate> anchorPayDate) {
        Utils.checkNotNull(anchorPayDate, "anchorPayDate");
        this.anchorPayDate = anchorPayDate;
        return this;
    }

    /**
     * ISO 8601 date (YYYY-MM-DD). Required for anchor and period dates in create, update, and preview
     * requests.
     */
    public PayScheduleUpdateRequest withAnchorEndOfPayPeriod(LocalDate anchorEndOfPayPeriod) {
        Utils.checkNotNull(anchorEndOfPayPeriod, "anchorEndOfPayPeriod");
        this.anchorEndOfPayPeriod = Optional.ofNullable(anchorEndOfPayPeriod);
        return this;
    }


    /**
     * ISO 8601 date (YYYY-MM-DD). Required for anchor and period dates in create, update, and preview
     * requests.
     */
    public PayScheduleUpdateRequest withAnchorEndOfPayPeriod(Optional<LocalDate> anchorEndOfPayPeriod) {
        Utils.checkNotNull(anchorEndOfPayPeriod, "anchorEndOfPayPeriod");
        this.anchorEndOfPayPeriod = anchorEndOfPayPeriod;
        return this;
    }

    /**
     * First pay day of the month (1–31). Required for Twice per month and Monthly; null for Every week and
     * Every other week.
     */
    public PayScheduleUpdateRequest withDay1(long day1) {
        Utils.checkNotNull(day1, "day1");
        this.day1 = JsonNullable.of(day1);
        return this;
    }

    /**
     * First pay day of the month (1–31). Required for Twice per month and Monthly; null for Every week and
     * Every other week.
     */
    public PayScheduleUpdateRequest withDay1(JsonNullable<Long> day1) {
        Utils.checkNotNull(day1, "day1");
        this.day1 = day1;
        return this;
    }

    /**
     * Second pay day of the month (1–31); only for Twice per month. Use 31 for last day of month. Null for
     * other frequencies.
     */
    public PayScheduleUpdateRequest withDay2(long day2) {
        Utils.checkNotNull(day2, "day2");
        this.day2 = JsonNullable.of(day2);
        return this;
    }

    /**
     * Second pay day of the month (1–31); only for Twice per month. Use 31 for last day of month. Null for
     * other frequencies.
     */
    public PayScheduleUpdateRequest withDay2(JsonNullable<Long> day2) {
        Utils.checkNotNull(day2, "day2");
        this.day2 = day2;
        return this;
    }

    /**
     * Custom name for the pay schedule; null clears it.
     */
    public PayScheduleUpdateRequest withCustomName(String customName) {
        Utils.checkNotNull(customName, "customName");
        this.customName = JsonNullable.of(customName);
        return this;
    }

    /**
     * Custom name for the pay schedule; null clears it.
     */
    public PayScheduleUpdateRequest withCustomName(JsonNullable<String> customName) {
        Utils.checkNotNull(customName, "customName");
        this.customName = customName;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PayScheduleUpdateRequest other = (PayScheduleUpdateRequest) o;
        return 
            Utils.enhancedDeepEquals(this.version, other.version) &&
            Utils.enhancedDeepEquals(this.autoPayroll, other.autoPayroll) &&
            Utils.enhancedDeepEquals(this.frequency, other.frequency) &&
            Utils.enhancedDeepEquals(this.anchorPayDate, other.anchorPayDate) &&
            Utils.enhancedDeepEquals(this.anchorEndOfPayPeriod, other.anchorEndOfPayPeriod) &&
            Utils.enhancedDeepEquals(this.day1, other.day1) &&
            Utils.enhancedDeepEquals(this.day2, other.day2) &&
            Utils.enhancedDeepEquals(this.customName, other.customName);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            version, autoPayroll, frequency,
            anchorPayDate, anchorEndOfPayPeriod, day1,
            day2, customName);
    }
    
    @Override
    public String toString() {
        return Utils.toString(PayScheduleUpdateRequest.class,
                "version", version,
                "autoPayroll", autoPayroll,
                "frequency", frequency,
                "anchorPayDate", anchorPayDate,
                "anchorEndOfPayPeriod", anchorEndOfPayPeriod,
                "day1", day1,
                "day2", day2,
                "customName", customName);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String version;

        private Optional<Boolean> autoPayroll = Optional.empty();

        private Optional<? extends PayScheduleFrequencyCreateUpdate> frequency = Optional.empty();

        private Optional<LocalDate> anchorPayDate = Optional.empty();

        private Optional<LocalDate> anchorEndOfPayPeriod = Optional.empty();

        private JsonNullable<Long> day1 = JsonNullable.undefined();

        private JsonNullable<Long> day2 = JsonNullable.undefined();

        private JsonNullable<String> customName = JsonNullable.undefined();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * Current version of the pay schedule from the GET response; required for optimistic concurrency.
         * Mismatch returns 409 Conflict.
         */
        public Builder version(String version) {
            Utils.checkNotNull(version, "version");
            this.version = version;
            return this;
        }


        /**
         * When true, Autopayroll is enabled and payroll runs automatically one day before payroll deadlines.
         * When false, payroll does not run automatically and must be run manually.
         * For API versions before 2025-11-15 the request field is auto_pilot.
         */
        public Builder autoPayroll(boolean autoPayroll) {
            Utils.checkNotNull(autoPayroll, "autoPayroll");
            this.autoPayroll = Optional.ofNullable(autoPayroll);
            return this;
        }

        /**
         * When true, Autopayroll is enabled and payroll runs automatically one day before payroll deadlines.
         * When false, payroll does not run automatically and must be run manually.
         * For API versions before 2025-11-15 the request field is auto_pilot.
         */
        public Builder autoPayroll(Optional<Boolean> autoPayroll) {
            Utils.checkNotNull(autoPayroll, "autoPayroll");
            this.autoPayroll = autoPayroll;
            return this;
        }


        /**
         * Pay frequency when creating or updating a schedule. Only weekly, bi-weekly, twice per month, and
         * monthly are supported via the API.
         * 
         * <p>- `Every week`: Weekly pay.
         * - `Every other week`: Biweekly pay.
         * - `Twice per month`: Two pay dates per month; require day_1 and day_2 (use 31 for last day of
         * month).
         * - `Monthly`: One pay date per month; require day_1 (1-31).
         */
        public Builder frequency(PayScheduleFrequencyCreateUpdate frequency) {
            Utils.checkNotNull(frequency, "frequency");
            this.frequency = Optional.ofNullable(frequency);
            return this;
        }

        /**
         * Pay frequency when creating or updating a schedule. Only weekly, bi-weekly, twice per month, and
         * monthly are supported via the API.
         * 
         * <p>- `Every week`: Weekly pay.
         * - `Every other week`: Biweekly pay.
         * - `Twice per month`: Two pay dates per month; require day_1 and day_2 (use 31 for last day of
         * month).
         * - `Monthly`: One pay date per month; require day_1 (1-31).
         */
        public Builder frequency(Optional<? extends PayScheduleFrequencyCreateUpdate> frequency) {
            Utils.checkNotNull(frequency, "frequency");
            this.frequency = frequency;
            return this;
        }


        /**
         * ISO 8601 date (YYYY-MM-DD). Required for anchor and period dates in create, update, and preview
         * requests.
         */
        public Builder anchorPayDate(LocalDate anchorPayDate) {
            Utils.checkNotNull(anchorPayDate, "anchorPayDate");
            this.anchorPayDate = Optional.ofNullable(anchorPayDate);
            return this;
        }

        /**
         * ISO 8601 date (YYYY-MM-DD). Required for anchor and period dates in create, update, and preview
         * requests.
         */
        public Builder anchorPayDate(Optional<LocalDate> anchorPayDate) {
            Utils.checkNotNull(anchorPayDate, "anchorPayDate");
            this.anchorPayDate = anchorPayDate;
            return this;
        }


        /**
         * ISO 8601 date (YYYY-MM-DD). Required for anchor and period dates in create, update, and preview
         * requests.
         */
        public Builder anchorEndOfPayPeriod(LocalDate anchorEndOfPayPeriod) {
            Utils.checkNotNull(anchorEndOfPayPeriod, "anchorEndOfPayPeriod");
            this.anchorEndOfPayPeriod = Optional.ofNullable(anchorEndOfPayPeriod);
            return this;
        }

        /**
         * ISO 8601 date (YYYY-MM-DD). Required for anchor and period dates in create, update, and preview
         * requests.
         */
        public Builder anchorEndOfPayPeriod(Optional<LocalDate> anchorEndOfPayPeriod) {
            Utils.checkNotNull(anchorEndOfPayPeriod, "anchorEndOfPayPeriod");
            this.anchorEndOfPayPeriod = anchorEndOfPayPeriod;
            return this;
        }


        /**
         * First pay day of the month (1–31). Required for Twice per month and Monthly; null for Every week and
         * Every other week.
         */
        public Builder day1(long day1) {
            Utils.checkNotNull(day1, "day1");
            this.day1 = JsonNullable.of(day1);
            return this;
        }

        /**
         * First pay day of the month (1–31). Required for Twice per month and Monthly; null for Every week and
         * Every other week.
         */
        public Builder day1(JsonNullable<Long> day1) {
            Utils.checkNotNull(day1, "day1");
            this.day1 = day1;
            return this;
        }


        /**
         * Second pay day of the month (1–31); only for Twice per month. Use 31 for last day of month. Null for
         * other frequencies.
         */
        public Builder day2(long day2) {
            Utils.checkNotNull(day2, "day2");
            this.day2 = JsonNullable.of(day2);
            return this;
        }

        /**
         * Second pay day of the month (1–31); only for Twice per month. Use 31 for last day of month. Null for
         * other frequencies.
         */
        public Builder day2(JsonNullable<Long> day2) {
            Utils.checkNotNull(day2, "day2");
            this.day2 = day2;
            return this;
        }


        /**
         * Custom name for the pay schedule; null clears it.
         */
        public Builder customName(String customName) {
            Utils.checkNotNull(customName, "customName");
            this.customName = JsonNullable.of(customName);
            return this;
        }

        /**
         * Custom name for the pay schedule; null clears it.
         */
        public Builder customName(JsonNullable<String> customName) {
            Utils.checkNotNull(customName, "customName");
            this.customName = customName;
            return this;
        }

        public PayScheduleUpdateRequest build() {

            return new PayScheduleUpdateRequest(
                version, autoPayroll, frequency,
                anchorPayDate, anchorEndOfPayPeriod, day1,
                day2, customName);
        }

    }
}
