/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gusto.embedded_api.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * PayrollEmployeeCompensationsTypeAmountType
 * 
 * <p>How to interpret the amount.
 */
public enum PayrollEmployeeCompensationsTypeAmountType {
    FIXED("fixed"),
    PERCENT("percent");

    @JsonValue
    private final String value;

    PayrollEmployeeCompensationsTypeAmountType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<PayrollEmployeeCompensationsTypeAmountType> fromValue(String value) {
        for (PayrollEmployeeCompensationsTypeAmountType o: PayrollEmployeeCompensationsTypeAmountType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

