/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gusto.embedded_api.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public enum PayrollPrepareSortBy {
    FIRST_NAME("first_name"),
    LAST_NAME("last_name");

    @JsonValue
    private final String value;

    PayrollPrepareSortBy(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<PayrollPrepareSortBy> fromValue(String value) {
        for (PayrollPrepareSortBy o: PayrollPrepareSortBy.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

