/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */


package com.gusto.embedded_api.models.components;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.gusto.embedded_api.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
/**
 * PayrollCreditBlockersTypeMetadata - Additional data associated with the unblock option.
 */

public class PayrollCreditBlockersTypeMetadata {

    @JsonCreator
    public PayrollCreditBlockersTypeMetadata() {
        
        
    }

    public final static Builder builder() {
        return new Builder();
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        return true;
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            );
    }
    
    @Override
    public String toString() {
        return Utils.toString(PayrollCreditBlockersTypeMetadata.class);
    }
    
    public final static class Builder {  
        
        private Builder() {
          // force use of static builder() method
        }
        
        public PayrollCreditBlockersTypeMetadata build() {
            return new PayrollCreditBlockersTypeMetadata(
                );
        }
    }
}

